DROP TABLE IF EXISTS `oc_emailtemplate_config`;

CREATE TABLE `oc_emailtemplate_config`(
  `emailtemplate_config_id` int(11) NOT NULL AUTO_INCREMENT,
  `emailtemplate_config_name` varchar(64) NOT NULL,
  `emailtemplate_config_email_width` varchar(12) NOT NULL,
  `emailtemplate_config_email_responsive` tinyint(1),
  `emailtemplate_config_body_bg_image` varchar(255),
  `emailtemplate_config_body_bg_image_repeat` varchar(32),
  `emailtemplate_config_body_bg_image_position` varchar(32),
  `emailtemplate_config_body_bg_color` varchar(32),
  `emailtemplate_config_body_font_family` varchar(128),
  `emailtemplate_config_body_font_size` smallint(6),
  `emailtemplate_config_body_font_color` varchar(32),
  `emailtemplate_config_body_link_color` varchar(32),
  `emailtemplate_config_body_heading_color` varchar(32),
  `emailtemplate_config_body_section_bg_color` varchar(32),
  `emailtemplate_config_page_align` enum('left','right','center') NOT NULL DEFAULT 'center',
  `emailtemplate_config_page_spacing` varchar(32),
  `emailtemplate_config_page_padding` varchar(32),
  `emailtemplate_config_page_bg_color` varchar(32),
  `emailtemplate_config_page_border_radius` varchar(64),
  `emailtemplate_config_page_border_top` varchar(128),
  `emailtemplate_config_page_border_bottom` varchar(128),
  `emailtemplate_config_page_border_left` varchar(128),
  `emailtemplate_config_page_border_right` varchar(128),
  `emailtemplate_config_page_footer_text` text,
  `emailtemplate_config_footer_text` text,
  `emailtemplate_config_footer_align` varchar(32),
  `emailtemplate_config_footer_font_color` varchar(32),
  `emailtemplate_config_footer_font_size` smallint(6),
  `emailtemplate_config_footer_bg_color` varchar(32),
  `emailtemplate_config_footer_height` smallint(6),
  `emailtemplate_config_footer_padding` varchar(32),
  `emailtemplate_config_footer_section_bg_color` varchar(32),
  `emailtemplate_config_footer_border_radius` varchar(64),
  `emailtemplate_config_footer_border_top` varchar(128),
  `emailtemplate_config_footer_border_bottom` varchar(128),
  `emailtemplate_config_footer_border_left` varchar(128),
  `emailtemplate_config_footer_border_right` varchar(128),
  `emailtemplate_config_footer_spacing` varchar(32),
  `emailtemplate_config_header_bg_color` varchar(32),
  `emailtemplate_config_header_html` TEXT NULL DEFAULT NULL DEFAULT '',
  `emailtemplate_config_header_bg_image` varchar(255),
  `emailtemplate_config_header_height` smallint(6),
  `emailtemplate_config_header_border_radius` varchar(32),
  `emailtemplate_config_header_border_top` varchar(128),
  `emailtemplate_config_header_border_bottom` varchar(128),
  `emailtemplate_config_header_border_left` varchar(128),
  `emailtemplate_config_header_border_right` varchar(128),
  `emailtemplate_config_header_section_bg_color` varchar(32),
  `emailtemplate_config_header_spacing` varchar(32),
  `emailtemplate_config_head_text` text,
  `emailtemplate_config_head_section_bg_color` varchar(32),
  `emailtemplate_config_view_browser_text` text,
  `emailtemplate_config_logo` varchar(255),
  `emailtemplate_config_logo_align` varchar(32),
  `emailtemplate_config_logo_font_color` varchar(32),
  `emailtemplate_config_logo_font_size` smallint(6),
  `emailtemplate_config_logo_height` smallint(6),
  `emailtemplate_config_logo_width` smallint(6),
  `emailtemplate_config_shadow_top` text,
  `emailtemplate_config_shadow_left` text,
  `emailtemplate_config_shadow_right` text,
  `emailtemplate_config_shadow_bottom` text,
  `emailtemplate_config_showcase` varchar(32),
  `emailtemplate_config_showcase_limit` smallint(6),
  `emailtemplate_config_showcase_selection` varchar(255),
  `emailtemplate_config_showcase_title` varchar(255),
  `emailtemplate_config_showcase_padding` varchar(32),
  `emailtemplate_config_showcase_cycle` tinyint(1),
  `emailtemplate_config_showcase_related` tinyint(1),
  `emailtemplate_config_showcase_bg_color` varchar(32),
  `emailtemplate_config_showcase_section_bg_color` varchar(32),
  `emailtemplate_config_showcase_per_row` tinyint(1) NOT NULL DEFAULT '4',
  `emailtemplate_config_showcase_border_radius` varchar(64),
  `emailtemplate_config_showcase_border_top` varchar(128),
  `emailtemplate_config_showcase_border_bottom` varchar(128),
  `emailtemplate_config_showcase_border_left` varchar(128),
  `emailtemplate_config_showcase_border_right` varchar(128),
  `emailtemplate_config_order_products` text,
  `emailtemplate_config_link_style` text,
  `emailtemplate_config_text_align` varchar(32) NOT NULL,
  `emailtemplate_config_wrapper_tpl` varchar(255) NOT NULL,
  `emailtemplate_config_theme` varchar(64) NOT NULL,
  `emailtemplate_config_style` varchar(64),
  `emailtemplate_config_version` varchar(64) NOT NULL,
  `emailtemplate_config_status` tinyint(1) NOT NULL,
  `emailtemplate_config_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emailtemplate_config_log` tinyint(1) NULL DEFAULT NULL,
  `emailtemplate_config_log_read` tinyint(1) NULL DEFAULT NULL,
  `emailtemplate_config_view_browser_theme` tinyint(1) NULL DEFAULT NULL,
  `customer_group_id` int(11) NOT NULL,
  `store_id` int(11) NOT NULL,
  `language_id` int(11) NOT NULL,
  PRIMARY KEY(`emailtemplate_config_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `oc_emailtemplate_config` SET 
`emailtemplate_config_id` = 1,
`emailtemplate_config_name` = '',
`emailtemplate_config_email_width` = '860px',
`emailtemplate_config_email_responsive` = 1,
`emailtemplate_config_wrapper_tpl` = '_main.tpl',
`emailtemplate_config_page_align` = 'center',
`emailtemplate_config_page_padding` = '30, 30, 40, 30',
`emailtemplate_config_page_bg_color` = '#FFFFFF',
`emailtemplate_config_body_bg_color` = '#F9F9F9',
`emailtemplate_config_body_font_size` = '14',
`emailtemplate_config_body_font_family` = 'Arial, \'Helvetica Neue\', Helvetica, sans-serif',
`emailtemplate_config_body_font_color` = '#333333',
`emailtemplate_config_body_link_color` = '#28B0EC',
`emailtemplate_config_body_heading_color` = '#079BDC',
`emailtemplate_config_page_border_left` = '1, #cccccc',
`emailtemplate_config_page_border_right` = '1, #cccccc',
`emailtemplate_config_footer_text` = 'YToxOntpOjE7czoyNTc6IiZsdDtwJmd0O1Bvd2VyZWQgYnkgJmx0O2EgaHJlZj0mcXVvdDtodHRwOi8vd3d3Lm9wZW5jYXJ0LmNvbSZxdW90OyB0YXJnZXQ9JnF1b3Q7X2JsYW5rJnF1b3Q7Jmd0O09wZW5jYXJ0Jmx0Oy9hJmd0OywgRGVzaWduZWQgQnkgJmx0O2EgaHJlZj0mcXVvdDtodHRwOi8vd3d3Lm9wZW5jYXJ0LXRlbXBsYXRlcy5jby51ayZxdW90OyB0YXJnZXQ9JnF1b3Q7X2JsYW5rJnF1b3Q7Jmd0O09wZW5DYXJ0LXRlbXBsYXRlcyZsdDsvYSZndDsuJmx0Oy9wJmd0Ow0KIjt9',
`emailtemplate_config_footer_align` = 'center',  
`emailtemplate_config_footer_font_size` = '12',
`emailtemplate_config_footer_font_color` = '#333333',
`emailtemplate_config_footer_padding` = '15, 0, 10, 0',
`emailtemplate_config_header_bg_color` = '#515151',
`emailtemplate_config_header_bg_image` = 'catalog/emailtemplate/head-bg.jpg', 
`emailtemplate_config_header_height` = 130,
`emailtemplate_config_header_border_left` = '1, #cccccc',
`emailtemplate_config_header_border_right` = '1, #cccccc',
`emailtemplate_config_view_browser_text` = 'YToxOntpOjE7czoxMzQ6IklmIHlvdSdyZSBoYXZpbmcgZGlmZmljdWx0eSB2aWV3aW5nIHRoaXMgZW1haWwgJmx0O2EgaHJlZj0mcXVvdDt7JHVybH0mcXVvdDsgdGFyZ2V0PSZxdW90O19ibGFuayZxdW90OyZndDtvcGVuIGluIGEgYnJvd3NlciZsdDsvYSZndDsuIjt9',
`emailtemplate_config_logo` = '{$store_logo}', 
`emailtemplate_config_logo_align` = 'center', 
`emailtemplate_config_logo_font_color` = '#032c6f', 
`emailtemplate_config_logo_font_size` = 30, 
`emailtemplate_config_logo_height` = 50,  
`emailtemplate_config_logo_width` = 268,
`emailtemplate_config_showcase` = 'latest', 
`emailtemplate_config_showcase_limit` = 4,
`emailtemplate_config_showcase_bg_color` = '#FFFFFF',
`emailtemplate_config_showcase_padding` = '10, 30, 10, 30',
`emailtemplate_config_showcase_title` = 'YToxOntpOjE7czoxNzoiWW91IG1heSBhbHNvIGxpa2UiO30=',
`emailtemplate_config_showcase_cycle` = 1,
`emailtemplate_config_showcase_related` = 1,
`emailtemplate_config_showcase_border_bottom` = '1, #cccccc',
`emailtemplate_config_showcase_border_left` = '1, #cccccc',
`emailtemplate_config_showcase_border_right` = '1, #cccccc',
`emailtemplate_config_text_align` = 'left',
`emailtemplate_config_theme` = 'default', 
`emailtemplate_config_style` = 'page',
`emailtemplate_config_version` = '2.9.3.9',
`emailtemplate_config_status` = 1, 
`emailtemplate_config_modified` = NOW(), 
`emailtemplate_config_log` = 0, 
`emailtemplate_config_log_read` = 0,
`customer_group_id` = 0, 
`store_id` = 0, 
`language_id` = 0;