INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '24', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'http://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('emailtemplate_log_id', 'auto', '650', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('telephone', 'auto', '01234556789', {_ID}),
('fax', 'auto', '1234556789', {_ID}),
('salt', 'auto', 'dRiHHHLUm', {_ID}),
('newsletter', 'auto', '1', {_ID}),
('address_id', 'auto', '0', {_ID}),
('custom_field', 'auto', '{\"1\":\"123456\"}', {_ID}),
('status', 'auto', '1', {_ID}),
('approved', 'auto', '1', {_ID}),
('safe', 'auto', '1', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('unsubscribe', 'auto', '<a href=\"http://localhost/index.php?route=account/newsletter/unsubscribe&code=ec05f0595e2e22a7eb0d93d66fd3900a\">Unsubscribe</a>', {_ID}),
('preheader_preview', 'auto', 'Your Store', {_ID}),
('view_browser', 'auto', '<p>fdfd</p>', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store', {_ID}),
('mail.text', 'auto', 'Hi Ben,', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_enabled', 'language', 'Enabled', {_ID}),
('text_disabled', 'language', 'Disabled', {_ID}),
('text_select_all', 'language', 'Select All', {_ID}),
('text_unselect_all', 'language', 'Unselect All', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_close', 'language', 'Close', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_confirm', 'language', 'Are you sure?', {_ID}),
('text_home', 'language', 'Home', {_ID}),
('button_add', 'language', 'Add New', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_save', 'language', 'Save', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cancel_recurring', 'language', 'Cancel Recurring Payments', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_clear', 'language', 'Clear', {_ID}),
('button_close', 'language', 'Close', {_ID}),
('button_enable', 'language', 'Enable', {_ID}),
('button_disable', 'language', 'Disable', {_ID}),
('button_filter', 'language', 'Filter', {_ID}),
('button_send', 'language', 'Send', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_copy', 'language', 'Copy', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_refresh', 'language', 'Refresh', {_ID}),
('button_export', 'language', 'Export', {_ID}),
('button_import', 'language', 'Import', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_rebuild', 'language', 'Rebuild', {_ID}),
('button_upload', 'language', 'Upload', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_invoice_print', 'language', 'Print Invoice', {_ID}),
('button_shipping_print', 'language', 'Print Shipping List', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_attribute_add', 'language', 'Add Attribute', {_ID}),
('button_banner_add', 'language', 'Add Banner', {_ID}),
('button_custom_field_value_add', 'language', 'Add Custom Field', {_ID}),
('button_product_add', 'language', 'Add Product', {_ID}),
('button_filter_add', 'language', 'Add Filter', {_ID}),
('button_option_add', 'language', 'Add Option', {_ID}),
('button_option_value_add', 'language', 'Add Option Value', {_ID}),
('button_recurring_add', 'language', 'Add Recurring', {_ID}),
('button_discount_add', 'language', 'Add Discount', {_ID}),
('button_special_add', 'language', 'Add Special', {_ID}),
('button_image_add', 'language', 'Add Image', {_ID}),
('button_geo_zone_add', 'language', 'Add Geo Zone', {_ID}),
('button_history_add', 'language', 'Add History', {_ID}),
('button_translation', 'language', 'Load Default Translation', {_ID}),
('button_translation_add', 'language', 'Add Translation', {_ID}),
('button_transaction_add', 'language', 'Add Transaction', {_ID}),
('button_route_add', 'language', 'Add Route', {_ID}),
('button_rule_add', 'language', 'Add Rule', {_ID}),
('button_module_add', 'language', 'Add Module', {_ID}),
('button_link_add', 'language', 'Add Link', {_ID}),
('button_approve', 'language', 'Approve', {_ID}),
('button_reset', 'language', 'Reset', {_ID}),
('button_generate', 'language', 'Generate', {_ID}),
('button_voucher_add', 'language', 'Add Voucher', {_ID}),
('button_reward_add', 'language', 'Add Reward Points', {_ID}),
('button_reward_remove', 'language', 'Remove Reward Points', {_ID}),
('button_commission_add', 'language', 'Add Commission', {_ID}),
('button_commission_remove', 'language', 'Remove Commission', {_ID}),
('button_credit_add', 'language', 'Add Credit', {_ID}),
('button_credit_remove', 'language', 'Remove Credit', {_ID}),
('button_ip_add', 'language', 'Add IP', {_ID}),
('button_parent', 'language', 'Parent', {_ID}),
('button_folder', 'language', 'New Folder', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_install', 'language', 'Install', {_ID}),
('button_uninstall', 'language', 'Uninstall', {_ID}),
('button_login', 'language', 'Login into Store', {_ID}),
('button_unlock', 'language', 'Unlock Account', {_ID}),
('button_link', 'language', 'Link', {_ID}),
('button_currency', 'language', 'Refresh Currency Values', {_ID}),
('button_apply', 'language', 'Apply', {_ID}),
('button_category_add', 'language', 'Add Category', {_ID}),
('button_order', 'language', 'View Order', {_ID}),
('button_order_recurring', 'language', 'View Recurring Order', {_ID}),
('tab_address', 'language', 'Address', {_ID}),
('tab_additional', 'language', 'Additional', {_ID}),
('tab_admin', 'language', 'Admin', {_ID}),
('tab_attribute', 'language', 'Attribute', {_ID}),
('tab_customer', 'language', 'Customer Details', {_ID}),
('tab_data', 'language', 'Data', {_ID}),
('tab_design', 'language', 'Design', {_ID}),
('tab_discount', 'language', 'Discount', {_ID}),
('tab_general', 'language', 'General', {_ID}),
('tab_history', 'language', 'History', {_ID}),
('tab_ftp', 'language', 'FTP', {_ID}),
('tab_ip', 'language', 'IP Addresses', {_ID}),
('tab_links', 'language', 'Links', {_ID}),
('tab_log', 'language', 'Log', {_ID}),
('tab_image', 'language', 'Image', {_ID}),
('tab_option', 'language', 'Option', {_ID}),
('tab_server', 'language', 'Server', {_ID}),
('tab_store', 'language', 'Store', {_ID}),
('tab_special', 'language', 'Special', {_ID}),
('tab_session', 'language', 'Session', {_ID}),
('tab_local', 'language', 'Local', {_ID}),
('tab_mail', 'language', 'Mail', {_ID}),
('tab_module', 'language', 'Module', {_ID}),
('tab_payment', 'language', 'Payment Details', {_ID}),
('tab_product', 'language', 'Products', {_ID}),
('tab_reward', 'language', 'Reward Points', {_ID}),
('tab_shipping', 'language', 'Shipping Details', {_ID}),
('tab_total', 'language', 'Totals', {_ID}),
('tab_transaction', 'language', 'Transactions', {_ID}),
('tab_voucher', 'language', 'Vouchers', {_ID}),
('tab_sale', 'language', 'Sales', {_ID}),
('tab_marketing', 'language', 'Marketing', {_ID}),
('tab_online', 'language', 'People Online', {_ID}),
('tab_activity', 'language', 'Recent Activity', {_ID}),
('tab_recurring', 'language', 'Recurring', {_ID}),
('tab_action', 'language', 'Action', {_ID}),
('tab_google', 'language', 'Google', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('entry_preheader', 'language', '<span data-toggle=\"tooltip\" title=\"Preview text shown before the email is opened\">Preheader Text:</span>', {_ID}),
('entry_template', 'language', 'Template:', {_ID}),
('text_success_sent', 'language', 'Your message has been successfully sent to %s recipients!', {_ID}),
('warning_template_content', 'language', 'Are you sure you want to change the template? This will clear all of the text inside the editor', {_ID}),
('warning_mail_recipients', 'language', 'Warning: no recipients could be found', {_ID}),
('heading_title', 'language', 'Mail', {_ID}),
('text_success', 'language', 'Your message has been successfully sent!', {_ID}),
('text_sent', 'language', 'Your message has been successfully sent to %s of %s recipients!', {_ID}),
('text_list', 'language', 'Mail List', {_ID}),
('text_newsletter', 'language', 'All Newsletter Subscribers', {_ID}),
('text_customer_all', 'language', 'All Customers', {_ID}),
('text_customer_group', 'language', 'Customer Group', {_ID}),
('text_customer', 'language', 'Customers', {_ID}),
('text_affiliate_all', 'language', 'All Affiliates', {_ID}),
('text_affiliate', 'language', 'Affiliates', {_ID}),
('text_product', 'language', 'Products', {_ID}),
('entry_store', 'language', 'From', {_ID}),
('entry_to', 'language', 'To', {_ID}),
('entry_customer_group', 'language', 'Customer Group', {_ID}),
('entry_customer', 'language', 'Customer', {_ID}),
('entry_affiliate', 'language', 'Affiliate', {_ID}),
('entry_product', 'language', 'Products', {_ID}),
('entry_subject', 'language', 'Subject', {_ID}),
('entry_message', 'language', 'Message', {_ID}),
('help_customer', 'language', '(Autocomplete)', {_ID}),
('help_affiliate', 'language', '(Autocomplete)', {_ID}),
('help_product', 'language', 'Send only to customers who have ordered products in the list. (Autocomplete)', {_ID}),
('error_permission', 'language', 'Warning: You do not have permission to send E-Mails!', {_ID}),
('error_subject', 'language', 'E-Mail Subject required!', {_ID}),
('error_message', 'language', 'E-Mail Message required!', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_unsubscribe', 'language', '<a href=\"%s\">Unsubscribe</a> from our newsletter', {_ID})