INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '0', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/', {_ID}),
('store_ssl', 'auto', 'http://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'You have been sent a gift certificate from Ben', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('voucher_id', 'auto', '1', {_ID}),
('order_id', 'auto', '0', {_ID}),
('from_name', 'auto', 'Ben', {_ID}),
('from_email', 'auto', 'user@localhost', {_ID}),
('to_name', 'auto', 'Bill', {_ID}),
('to_email', 'auto', 'bill@abc.com', {_ID}),
('voucher_theme_id', 'auto', '7', {_ID}),
('message', 'auto', 'Happy Birthday!', {_ID}),
('amount', 'auto', '$10.00', {_ID}),
('status', 'auto', '1', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('image', 'auto', 'http://localhost/image/catalog/demo/gift-voucher-birthday.jpg', {_ID}),
('name', 'auto', 'Birthday', {_ID}),
('image_width', 'auto', '300', {_ID}),
('image_height', 'auto', '199', {_ID}),
('preheader_preview', 'auto', 'This Gift Certificate has been sent to you by Ben', {_ID}),
('mail.to', 'auto', 'bill@abc.com', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'You have been sent a gift certificate from Ben', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_enabled', 'language', 'Enabled', {_ID}),
('text_disabled', 'language', 'Disabled', {_ID}),
('text_select_all', 'language', 'Select All', {_ID}),
('text_unselect_all', 'language', 'Unselect All', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_close', 'language', 'Close', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_confirm', 'language', 'Are you sure?', {_ID}),
('text_home', 'language', 'Home', {_ID}),
('button_add', 'language', 'Add New', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_save', 'language', 'Save', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cancel_recurring', 'language', 'Cancel Recurring Payments', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_clear', 'language', 'Clear', {_ID}),
('button_close', 'language', 'Close', {_ID}),
('button_enable', 'language', 'Enable', {_ID}),
('button_disable', 'language', 'Disable', {_ID}),
('button_filter', 'language', 'Filter', {_ID}),
('button_send', 'language', 'Send', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_copy', 'language', 'Copy', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_refresh', 'language', 'Refresh', {_ID}),
('button_export', 'language', 'Export', {_ID}),
('button_import', 'language', 'Import', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_rebuild', 'language', 'Rebuild', {_ID}),
('button_upload', 'language', 'Upload', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_invoice_print', 'language', 'Print Invoice', {_ID}),
('button_shipping_print', 'language', 'Print Shipping List', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_attribute_add', 'language', 'Add Attribute', {_ID}),
('button_banner_add', 'language', 'Add Banner', {_ID}),
('button_custom_field_value_add', 'language', 'Add Custom Field', {_ID}),
('button_product_add', 'language', 'Add Product', {_ID}),
('button_filter_add', 'language', 'Add Filter', {_ID}),
('button_option_add', 'language', 'Add Option', {_ID}),
('button_option_value_add', 'language', 'Add Option Value', {_ID}),
('button_recurring_add', 'language', 'Add Recurring', {_ID}),
('button_discount_add', 'language', 'Add Discount', {_ID}),
('button_special_add', 'language', 'Add Special', {_ID}),
('button_image_add', 'language', 'Add Image', {_ID}),
('button_geo_zone_add', 'language', 'Add Geo Zone', {_ID}),
('button_history_add', 'language', 'Add History', {_ID}),
('button_translation', 'language', 'Load Default Translation', {_ID}),
('button_translation_add', 'language', 'Add Translation', {_ID}),
('button_transaction_add', 'language', 'Add Transaction', {_ID}),
('button_route_add', 'language', 'Add Route', {_ID}),
('button_rule_add', 'language', 'Add Rule', {_ID}),
('button_module_add', 'language', 'Add Module', {_ID}),
('button_link_add', 'language', 'Add Link', {_ID}),
('button_approve', 'language', 'Approve', {_ID}),
('button_reset', 'language', 'Reset', {_ID}),
('button_generate', 'language', 'Generate', {_ID}),
('button_voucher_add', 'language', 'Add Voucher', {_ID}),
('button_reward_add', 'language', 'Add Reward Points', {_ID}),
('button_reward_remove', 'language', 'Remove Reward Points', {_ID}),
('button_commission_add', 'language', 'Add Commission', {_ID}),
('button_commission_remove', 'language', 'Remove Commission', {_ID}),
('button_credit_add', 'language', 'Add Credit', {_ID}),
('button_credit_remove', 'language', 'Remove Credit', {_ID}),
('button_ip_add', 'language', 'Add IP', {_ID}),
('button_parent', 'language', 'Parent', {_ID}),
('button_folder', 'language', 'New Folder', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_install', 'language', 'Install', {_ID}),
('button_uninstall', 'language', 'Uninstall', {_ID}),
('button_login', 'language', 'Login into Store', {_ID}),
('button_unlock', 'language', 'Unlock Account', {_ID}),
('button_link', 'language', 'Link', {_ID}),
('button_currency', 'language', 'Refresh Currency Values', {_ID}),
('button_apply', 'language', 'Apply', {_ID}),
('button_category_add', 'language', 'Add Category', {_ID}),
('button_order', 'language', 'View Order', {_ID}),
('button_order_recurring', 'language', 'View Recurring Order', {_ID}),
('tab_address', 'language', 'Address', {_ID}),
('tab_additional', 'language', 'Additional', {_ID}),
('tab_admin', 'language', 'Admin', {_ID}),
('tab_attribute', 'language', 'Attribute', {_ID}),
('tab_customer', 'language', 'Customer Details', {_ID}),
('tab_data', 'language', 'Data', {_ID}),
('tab_design', 'language', 'Design', {_ID}),
('tab_discount', 'language', 'Discount', {_ID}),
('tab_general', 'language', 'General', {_ID}),
('tab_history', 'language', 'History', {_ID}),
('tab_ftp', 'language', 'FTP', {_ID}),
('tab_ip', 'language', 'IP Addresses', {_ID}),
('tab_links', 'language', 'Links', {_ID}),
('tab_log', 'language', 'Log', {_ID}),
('tab_image', 'language', 'Image', {_ID}),
('tab_option', 'language', 'Option', {_ID}),
('tab_server', 'language', 'Server', {_ID}),
('tab_store', 'language', 'Store', {_ID}),
('tab_special', 'language', 'Special', {_ID}),
('tab_session', 'language', 'Session', {_ID}),
('tab_local', 'language', 'Local', {_ID}),
('tab_mail', 'language', 'Mail', {_ID}),
('tab_module', 'language', 'Module', {_ID}),
('tab_payment', 'language', 'Payment Details', {_ID}),
('tab_product', 'language', 'Products', {_ID}),
('tab_reward', 'language', 'Reward Points', {_ID}),
('tab_shipping', 'language', 'Shipping Details', {_ID}),
('tab_total', 'language', 'Totals', {_ID}),
('tab_transaction', 'language', 'Transactions', {_ID}),
('tab_voucher', 'language', 'Vouchers', {_ID}),
('tab_sale', 'language', 'Sales', {_ID}),
('tab_marketing', 'language', 'Marketing', {_ID}),
('tab_online', 'language', 'People Online', {_ID}),
('tab_activity', 'language', 'Recent Activity', {_ID}),
('tab_recurring', 'language', 'Recurring', {_ID}),
('tab_action', 'language', 'Action', {_ID}),
('tab_google', 'language', 'Google', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('heading_title', 'language', 'Gift Vouchers', {_ID}),
('text_success', 'language', 'Success: You have modified vouchers!', {_ID}),
('text_list', 'language', 'Gift Voucher List', {_ID}),
('text_add', 'language', 'Add Gift Voucher', {_ID}),
('text_edit', 'language', 'Edit Gift Voucher', {_ID}),
('text_sent', 'language', 'Success: Gift Voucher e-mail has been sent!', {_ID}),
('column_name', 'language', 'Voucher Name', {_ID}),
('column_code', 'language', 'Code', {_ID}),
('column_from', 'language', 'From', {_ID}),
('column_to', 'language', 'To', {_ID}),
('column_theme', 'language', 'Theme', {_ID}),
('column_amount', 'language', 'Amount', {_ID}),
('column_status', 'language', 'Status', {_ID}),
('column_order_id', 'language', 'Order ID', {_ID}),
('column_customer', 'language', 'Customer', {_ID}),
('column_date_added', 'language', 'Date Added', {_ID}),
('column_action', 'language', 'Action', {_ID}),
('entry_code', 'language', 'Code', {_ID}),
('entry_from_name', 'language', 'From Name', {_ID}),
('entry_from_email', 'language', 'From E-Mail', {_ID}),
('entry_to_name', 'language', 'To Name', {_ID}),
('entry_to_email', 'language', 'To E-Mail', {_ID}),
('entry_theme', 'language', 'Theme', {_ID}),
('entry_message', 'language', 'Message', {_ID}),
('entry_amount', 'language', 'Amount', {_ID}),
('entry_status', 'language', 'Status', {_ID}),
('help_code', 'language', 'The code the customer enters to activate the voucher.', {_ID}),
('error_selection', 'language', 'Warning: No vouchers selected!', {_ID}),
('error_permission', 'language', 'Warning: You do not have permission to modify vouchers!', {_ID}),
('error_exists', 'language', 'Warning: Voucher code is already in use!', {_ID}),
('error_code', 'language', 'Code must be between 3 and 10 characters!', {_ID}),
('error_to_name', 'language', 'Recipient\'s Name must be between 1 and 64 characters!', {_ID}),
('error_from_name', 'language', 'Your Name must be between 1 and 64 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_amount', 'language', 'Amount must be greater than or equal to 1!', {_ID}),
('error_order', 'language', 'Warning: This voucher cannot be deleted as it is part of an <a href=\"%s\">order</a>!', {_ID}),
('text_subject', 'language', 'You have been sent a gift certificate from %s', {_ID}),
('text_greeting', 'language', 'Congratulations, You have received a Gift Certificate worth %s', {_ID}),
('text_from', 'language', 'This Gift Certificate has been sent to you by %s', {_ID}),
('text_message', 'language', 'With a message saying', {_ID}),
('text_redeem', 'language', 'To redeem this Gift Certificate, write down the redemption code which is <b>%s</b> then click on the the link below and purchase the product you wish to use this gift certificate on. You can enter the gift certificate code on the shopping cart page before you click checkout.', {_ID}),
('text_footer', 'language', 'Please reply to this email if you have any questions.', {_ID}),
('text_heading', 'language', 'Gift Voucher', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_unsubscribe', 'language', '<a href=\"%s\">Unsubscribe</a> from our newsletter', {_ID})