INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_tax', 'auto', '1', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_url', 'auto', 'http://localhost/', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('customer_id', 'auto', '23', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('customer_group.customer_group_id', 'auto', '1', {_ID}),
('customer_group.approval', 'auto', '0', {_ID}),
('customer_group.sort_order', 'auto', '1', {_ID}),
('customer_group.language_id', 'auto', '1', {_ID}),
('customer_group.name', 'auto', 'Default', {_ID}),
('customer_group.description', 'auto', 'test', {_ID}),
('order_id', 'auto', '38', {_ID}),
('invoice_no', 'auto', '11', {_ID}),
('invoice_prefix', 'auto', 'INV-2017-00', {_ID}),
('affiliate_id', 'auto', '0', {_ID}),
('weight', 'auto', '0.00000000', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('telephone', 'auto', '0123456789', {_ID}),
('fax', 'auto', '0113456789', {_ID}),
('custom_field.1', 'auto', '123456', {_ID}),
('payment_firstname', 'auto', 'Ben', {_ID}),
('payment_lastname', 'auto', 'Johnson', {_ID}),
('payment_company', 'auto', 'Opencart-Templates', {_ID}),
('payment_address_1', 'auto', '12 Long Lane', {_ID}),
('payment_address_2', 'auto', 'Westminster ', {_ID}),
('payment_postcode', 'auto', 'SW1A 0AA', {_ID}),
('payment_city', 'auto', 'London', {_ID}),
('payment_zone_id', 'auto', '3553', {_ID}),
('payment_zone', 'auto', 'Greater London', {_ID}),
('payment_zone_code', 'auto', 'LDN', {_ID}),
('payment_country_id', 'auto', '222', {_ID}),
('payment_country', 'auto', 'United Kingdom', {_ID}),
('payment_iso_code_2', 'auto', 'GB', {_ID}),
('payment_iso_code_3', 'auto', 'GBR', {_ID}),
('payment_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('payment_method', 'auto', 'Cash On Delivery', {_ID}),
('payment_code', 'auto', 'cod', {_ID}),
('shipping_firstname', 'auto', 'Ben', {_ID}),
('shipping_lastname', 'auto', 'Johnson', {_ID}),
('shipping_company', 'auto', 'Opencart-Templates', {_ID}),
('shipping_address_1', 'auto', '12 Long Lane', {_ID}),
('shipping_address_2', 'auto', 'Westminster ', {_ID}),
('shipping_postcode', 'auto', 'SW1A 0AA', {_ID}),
('shipping_city', 'auto', 'London', {_ID}),
('shipping_zone_id', 'auto', '3553', {_ID}),
('shipping_zone', 'auto', 'Greater London', {_ID}),
('shipping_zone_code', 'auto', 'LDN', {_ID}),
('shipping_country_id', 'auto', '222', {_ID}),
('shipping_country', 'auto', 'United Kingdom', {_ID}),
('shipping_iso_code_2', 'auto', 'GB', {_ID}),
('shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('shipping_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('shipping_code', 'auto', 'flat.flat', {_ID}),
('comment', 'auto', '<p>Hi Ben,</p><p>Your order has been updated with status: shipped. </p><p>Please allow 3-5 working days for this to arrive.<br></p>', {_ID}),
('products', 'auto_serialize', 'YTozOntpOjA7YToxNzp7czoxMDoicHJvZHVjdF9pZCI7czoyOiI0OCI7czozOiJ1cmwiO3M6MTA3OiJodHRwOi8vMTI3LjAuMC4xL29wZW5jYXJ0X2FkdmFuY2VkL29wZW5jYXJ0X2FkdmFuY2VkXzIzMDAvaW5kZXgucGhwP3JvdXRlPXByb2R1Y3QvcHJvZHVjdCZhbXA7cHJvZHVjdF9pZD00OCI7czo1OiJpbWFnZSI7czoxMDc6Imh0dHA6Ly8xMjcuMC4wLjEvb3BlbmNhcnRfYWR2YW5jZWQvb3BlbmNhcnRfYWR2YW5jZWRfMjMwMC9pbWFnZS9jYWNoZS9jYXRhbG9nL2RlbW8vaXBvZF9jbGFzc2ljXzEtNTB4NTAuanBnIjtzOjY6IndlaWdodCI7czo2OiIxLjAwa2ciO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjIwMjoiDQoJDQoJCQ0KCQkJTW9yZSByb29tIHRvIG1vdmUuDQoJCQ0KCQkJV2l0aCA4MEdCIG9yIDE2MEdCIG9mIHN0b3JhZ2UgYW5kIHVwIHRvIDQwIGhvdXJzIG9mIGJhdHRlcnkgbGlmZSwgdGhlIG5ldyBpUG9kIGNsYXNzaWMgbGV0cyB5b3UgZW5qb3kgdXAgdG8gNDAsMDAwIHNvbmdzIG9yIHVwIHRvIDIwMCBob3VycyBvZiB2aWRlbyBvciBhbnkgY29tYmkuLiI7czoxMjoibWFudWZhY3R1cmVyIjtzOjU6IkFwcGxlIjtzOjM6InNrdSI7czo2OiJ0ZXN0IDEiO3M6MTI6InN0b2NrX3N0YXR1cyI7czoxMjoiT3V0IE9mIFN0b2NrIjtzOjE0OiJzdG9ja19zdWJ0cmFjdCI7czoxOiIxIjtzOjE0OiJzdG9ja19xdWFudGl0eSI7aTo5ODA7czoxNToic3RvY2tfYmFja29yZGVyIjtiOjA7czo0OiJuYW1lIjtzOjEyOiJpUG9kIENsYXNzaWMiO3M6NToibW9kZWwiO3M6MTA6InByb2R1Y3QgMjAiO3M6Njoib3B0aW9uIjthOjA6e31zOjg6InF1YW50aXR5IjtzOjE6IjEiO3M6NToicHJpY2UiO3M6NzoiJDEyMi4wMCI7czo1OiJ0b3RhbCI7czo3OiIkMTIyLjAwIjt9aToxO2E6MTc6e3M6MTA6InByb2R1Y3RfaWQiO3M6MjoiMjgiO3M6MzoidXJsIjtzOjEwNzoiaHR0cDovLzEyNy4wLjAuMS9vcGVuY2FydF9hZHZhbmNlZC9vcGVuY2FydF9hZHZhbmNlZF8yMzAwL2luZGV4LnBocD9yb3V0ZT1wcm9kdWN0L3Byb2R1Y3QmYW1wO3Byb2R1Y3RfaWQ9MjgiO3M6NToiaW1hZ2UiO3M6MTA3OiJodHRwOi8vMTI3LjAuMC4xL29wZW5jYXJ0X2FkdmFuY2VkL29wZW5jYXJ0X2FkdmFuY2VkXzIzMDAvaW1hZ2UvY2FjaGUvY2F0YWxvZy9kZW1vL2h0Y190b3VjaF9oZF8xLTUweDUwLmpwZyI7czo2OiJ3ZWlnaHQiO3M6NzoiMTQ2LjQwZyI7czoxMToiZGVzY3JpcHRpb24iO3M6MjAyOiINCglIVEMgVG91Y2ggLSBpbiBIaWdoIERlZmluaXRpb24uIFdhdGNoIG11c2ljIHZpZGVvcyBhbmQgc3RyZWFtaW5nIGNvbnRlbnQgaW4gYXdlLWluc3BpcmluZyBoaWdoIGRlZmluaXRpb24gY2xhcml0eSBmb3IgYSBtb2JpbGUgZXhwZXJpZW5jZSB5b3UgbmV2ZXIgdGhvdWdodCBwb3NzaWJsZS4gU2VkdWN0aXZlbHkgc2xlZWssIHRoZSBIVEMgVG91Yy4uIjtzOjEyOiJtYW51ZmFjdHVyZXIiO3M6MzoiSFRDIjtzOjM6InNrdSI7czowOiIiO3M6MTI6InN0b2NrX3N0YXR1cyI7czo4OiJJbiBTdG9jayI7czoxNDoic3RvY2tfc3VidHJhY3QiO3M6MToiMSI7czoxNDoic3RvY2tfcXVhbnRpdHkiO2k6OTM5O3M6MTU6InN0b2NrX2JhY2tvcmRlciI7YjowO3M6NDoibmFtZSI7czoxMjoiSFRDIFRvdWNoIEhEIjtzOjU6Im1vZGVsIjtzOjk6IlByb2R1Y3QgMSI7czo2OiJvcHRpb24iO2E6MDp7fXM6ODoicXVhbnRpdHkiO3M6MToiMiI7czo1OiJwcmljZSI7czo3OiIkMTIyLjAwIjtzOjU6InRvdGFsIjtzOjc6IiQyNDQuMDAiO31pOjI7YToxNzp7czoxMDoicHJvZHVjdF9pZCI7czoyOiI0MyI7czozOiJ1cmwiO3M6MTA3OiJodHRwOi8vMTI3LjAuMC4xL29wZW5jYXJ0X2FkdmFuY2VkL29wZW5jYXJ0X2FkdmFuY2VkXzIzMDAvaW5kZXgucGhwP3JvdXRlPXByb2R1Y3QvcHJvZHVjdCZhbXA7cHJvZHVjdF9pZD00MyI7czo1OiJpbWFnZSI7czoxMDI6Imh0dHA6Ly8xMjcuMC4wLjEvb3BlbmNhcnRfYWR2YW5jZWQvb3BlbmNhcnRfYWR2YW5jZWRfMjMwMC9pbWFnZS9jYWNoZS9jYXRhbG9nL2RlbW8vbWFjYm9va18xLTUweDUwLmpwZyI7czo2OiJ3ZWlnaHQiO2k6MDtzOjExOiJkZXNjcmlwdGlvbiI7czoyMDI6Ig0KCQ0KCQlJbnRlbCBDb3JlIDIgRHVvIHByb2Nlc3Nvcg0KCQ0KCQlQb3dlcmVkIGJ5IGFuIEludGVsIENvcmUgMiBEdW8gcHJvY2Vzc29yIGF0IHNwZWVkcyB1cCB0byAyLjE2R0h6LCB0aGUgbmV3IE1hY0Jvb2sgaXMgdGhlIGZhc3Rlc3QgZXZlci4NCgkNCgkJMUdCIG1lbW9yeSwgbGFyZ2VyIGhhcmQgZHJpdmVzDQoJDQoJCVRoZSBuZXcgTWFjQm9vLi4iO3M6MTI6Im1hbnVmYWN0dXJlciI7czo1OiJBcHBsZSI7czozOiJza3UiO3M6MDoiIjtzOjEyOiJzdG9ja19zdGF0dXMiO3M6MTI6Ik91dCBPZiBTdG9jayI7czoxNDoic3RvY2tfc3VidHJhY3QiO3M6MToiMSI7czoxNDoic3RvY2tfcXVhbnRpdHkiO2k6OTI4O3M6MTU6InN0b2NrX2JhY2tvcmRlciI7YjowO3M6NDoibmFtZSI7czo3OiJNYWNCb29rIjtzOjU6Im1vZGVsIjtzOjEwOiJQcm9kdWN0IDE2IjtzOjY6Im9wdGlvbiI7YTowOnt9czo4OiJxdWFudGl0eSI7czoxOiIxIjtzOjU6InByaWNlIjtzOjc6IiQ2MDIuMDAiO3M6NToidG90YWwiO3M6NzoiJDYwMi4wMCI7fX0=', {_ID}),
('totals', 'auto_serialize', 'YTo2OntpOjA7YToyOntzOjU6InRpdGxlIjtzOjk6IlN1Yi1Ub3RhbCI7czo0OiJ0ZXh0IjtzOjc6IiQ4MDAuMDAiO31pOjE7YToyOntzOjU6InRpdGxlIjtzOjE4OiJGbGF0IFNoaXBwaW5nIFJhdGUiO3M6NDoidGV4dCI7czo1OiIkNS4wMCI7fWk6MjthOjI6e3M6NToidGl0bGUiO3M6MTM6IkNvdXBvbiAoMTExMSkiO3M6NDoidGV4dCI7czo3OiIkLTEwLjAwIjt9aTozO2E6Mjp7czo1OiJ0aXRsZSI7czoxNToiRWNvIFRheCAoLTIuMDApIjtzOjQ6InRleHQiO3M6NjoiJDEwLjAwIjt9aTo0O2E6Mjp7czo1OiJ0aXRsZSI7czo5OiJWQVQgKDIwJSkiO3M6NDoidGV4dCI7czo3OiIkMTU5LjAwIjt9aTo1O2E6Mjp7czo1OiJ0aXRsZSI7czo1OiJUb3RhbCI7czo0OiJ0ZXh0IjtzOjc6IiQ5NjQuMDAiO319', {_ID}),
('total', 'auto', '964.0000', {_ID}),
('order_status_id', 'auto', '5', {_ID}),
('order_status', 'auto', 'Complete', {_ID}),
('order_products_file', 'auto', 'order_products/default.tpl', {_ID}),
('commission', 'auto', '0.0000', {_ID}),
('language_code', 'auto', 'en-gb', {_ID}),
('currency_id', 'auto', '2', {_ID}),
('currency_code', 'auto', 'USD', {_ID}),
('currency_value', 'auto', '1.00000000', {_ID}),
('ip', 'auto', 'localhost', {_ID}),
('user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36', {_ID}),
('accept_language', 'auto', 'en-GB,en-US;q=0.8,en;q=0.6', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('date_modified', 'auto', '2017-04-20 11:18:46', {_ID}),
('prev_order_status_id', 'auto', '1', {_ID}),
('text_update_heading', 'auto', 'Your Store - Order Update 38', {_ID}),
('order_comment', 'auto', 'Test comment<br /><br />With line break', {_ID}),
('instruction', 'auto', '<p>Hi Ben, your order has been shipped. </p><p>Please allow 3-5 working days for this to arrive.<br></p>', {_ID}),
('order_url', 'auto', 'http://localhost/index.php?route=account/order/info&order_id=38', {_ID}),
('custom_field_2_name', 'auto', 'testing', {_ID}),
('custom_field_2_value', 'auto', 'Testing custom field', {_ID}),
('custom_field_1_name', 'auto', 'VAT No', {_ID}),
('custom_field_1_value', 'auto', '123456', {_ID}),
('order_subject_products', 'auto', 'iPod Classic, HTC Touch HD,...', {_ID}),
('preheader_preview', 'auto', 'Your order has been updated to Complete', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store - Order Update 38', {_ID}),
('mail.text', 'auto', 'Order ID: 38\nDate Ordered: 16/04/2017\n\nYour order has been updated to the following status:\n\nComplete\n\nTo view your order click on the link below:\nhttp://localhost/index.php?route=account/order/info&order_id=38\n\nThe comments for your order are:\n\nHi Ben, your order has been shipped. Please allow 3-5 working days for this to arrive.\n\nPlease reply to this email if you have any questions.', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_product', 'auto', 'Product', {_ID}),
('text_model', 'auto', 'Model', {_ID}),
('text_quantity', 'auto', 'Quantity', {_ID}),
('text_price', 'auto', 'Price', {_ID}),
('text_total', 'auto', 'Total', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('text_success', 'language', 'Success: You have modified orders!', {_ID}),
('error_permission', 'language', 'Warning: You do not have permission to access the API!', {_ID}),
('error_customer', 'language', 'Warning: Customer details needs to be set!', {_ID}),
('error_payment_address', 'language', 'Warning: Payment address required!', {_ID}),
('error_payment_method', 'language', 'Warning: Payment method required!', {_ID}),
('error_no_payment', 'language', 'Warning: No Payment options are available!', {_ID}),
('error_shipping_address', 'language', 'Warning: Shipping address required!', {_ID}),
('error_shipping_method', 'language', 'Warning: Shipping method required!', {_ID}),
('error_no_shipping', 'language', 'Warning: No Shipping options are available!', {_ID}),
('error_stock', 'language', 'Warning: Products marked with *** are not available in the desired quantity or not in stock!', {_ID}),
('error_minimum', 'language', 'Warning: Minimum order amount for %s is %s!', {_ID}),
('error_not_found', 'language', 'Warning: Order could not be found!', {_ID}),
('text_affiliate', 'language', 'Affiliate:', {_ID}),
('text_backorder_quantity', 'language', 'Back Order', {_ID}),
('text_customer_group', 'language', 'Customer group:', {_ID}),
('text_id', 'language', 'ID', {_ID}),
('text_invoice_no', 'language', 'Invoice No:', {_ID}),
('text_new_heading', 'language', 'Order Confirmation', {_ID}),
('text_new_preheader', 'language', 'Thank you for your order at {$store_name}.', {_ID}),
('text_new_subject_admin', 'language', '{$store_name} - Order {$order_id}: \'{$order_subject_products}\'', {_ID}),
('text_new_subject_customer', 'language', '{$store_name} - Order of \'{$order_subject_products}\'', {_ID}),
('text_order_link', 'language', 'To view this order click on the link below:', {_ID}),
('text_sku', 'language', 'SKU', {_ID}),
('text_stock_quantity', 'language', 'In Stock', {_ID}),
('text_update_preheader', 'language', 'Your order has been updated to {$order_status}', {_ID}),
('text_new_subject', 'language', '%s - Order %s', {_ID}),
('text_new_greeting', 'language', 'Thank you for your interest in %s products. Your order has been received and will be processed once payment has been confirmed.', {_ID}),
('text_new_received', 'language', 'You have received an order.', {_ID}),
('text_new_link', 'language', 'To view your order click on the link below:', {_ID}),
('text_new_order_detail', 'language', 'Order Details', {_ID}),
('text_new_instruction', 'language', 'Instructions', {_ID}),
('text_new_order_id', 'language', 'Order ID:', {_ID}),
('text_new_date_added', 'language', 'Date Added:', {_ID}),
('text_new_order_status', 'language', 'Order Status:', {_ID}),
('text_new_payment_method', 'language', 'Payment Method:', {_ID}),
('text_new_shipping_method', 'language', 'Shipping Method:', {_ID}),
('text_new_email', 'language', 'E-mail:', {_ID}),
('text_new_telephone', 'language', 'Telephone:', {_ID}),
('text_new_ip', 'language', 'IP Address:', {_ID}),
('text_new_payment_address', 'language', 'Payment Address', {_ID}),
('text_new_shipping_address', 'language', 'Shipping Address', {_ID}),
('text_new_products', 'language', 'Products', {_ID}),
('text_new_product', 'language', 'Product', {_ID}),
('text_new_model', 'language', 'Model', {_ID}),
('text_new_quantity', 'language', 'Quantity', {_ID}),
('text_new_price', 'language', 'Price', {_ID}),
('text_new_order_total', 'language', 'Order Totals', {_ID}),
('text_new_total', 'language', 'Total', {_ID}),
('text_new_download', 'language', 'Once your payment has been confirmed you can click on the link below to access your downloadable products:', {_ID}),
('text_new_comment', 'language', 'The comments for your order are:', {_ID}),
('text_new_footer', 'language', 'Please reply to this e-mail if you have any questions.', {_ID}),
('text_update_subject', 'language', '%s - Order Update %s', {_ID}),
('text_update_order', 'language', 'Order ID:', {_ID}),
('text_update_date_added', 'language', 'Date Ordered:', {_ID}),
('text_update_order_status', 'language', 'Your order has been updated to the following status:', {_ID}),
('text_update_comment', 'language', 'The comments for your order are:', {_ID}),
('text_update_link', 'language', 'To view your order click on the link below:', {_ID}),
('text_update_footer', 'language', 'Please reply to this email if you have any questions.', {_ID}),
('text_rating', 'language', 'Rating', {_ID});