INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('error_telephone', 'language', 'Telephone must be between 3 and 32 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_lastname', 'language', 'Last Name must be between 1 and 32 characters!', {_ID}),
('error_firstname', 'language', 'First Name must be between 1 and 32 characters!', {_ID}),
('error_order_id', 'language', 'Order ID required!', {_ID}),
('error_permission', 'language', 'Warning: You do not have permission to modify returns!', {_ID}),
('error_warning', 'language', 'Warning: Please check the form carefully for errors!', {_ID}),
('help_product', 'language', '(Autocomplete)', {_ID}),
('entry_date_modified', 'language', 'Date Modified', {_ID}),
('entry_date_added', 'language', 'Date Added', {_ID}),
('entry_return_id', 'language', 'Return ID', {_ID}),
('entry_notify', 'language', 'Notify Customer', {_ID}),
('entry_return_status', 'language', 'Return Status', {_ID}),
('entry_return_action', 'language', 'Return Action', {_ID}),
('entry_return_reason', 'language', 'Return Reason', {_ID}),
('entry_comment', 'language', 'Comment', {_ID}),
('entry_quantity', 'language', 'Quantity', {_ID}),
('entry_opened', 'language', 'Opened', {_ID}),
('entry_model', 'language', 'Model', {_ID}),
('entry_product', 'language', 'Product', {_ID}),
('entry_email', 'language', 'E-Mail', {_ID}),
('entry_telephone', 'language', 'Telephone', {_ID}),
('entry_firstname', 'language', 'First Name', {_ID}),
('entry_lastname', 'language', 'Last Name', {_ID}),
('column_action', 'language', 'Action', {_ID}),
('entry_customer', 'language', 'Customer', {_ID}),
('entry_order_id', 'language', 'Order ID', {_ID}),
('entry_date_ordered', 'language', 'Order Date', {_ID}),
('column_notify', 'language', 'Customer Notified', {_ID}),
('column_comment', 'language', 'Comment', {_ID}),
('column_date_modified', 'language', 'Date Modified', {_ID}),
('column_status', 'language', 'Status', {_ID}),
('column_date_added', 'language', 'Date Added', {_ID}),
('column_product', 'language', 'Product', {_ID}),
('column_model', 'language', 'Model', {_ID}),
('column_order_id', 'language', 'Order ID', {_ID}),
('column_customer', 'language', 'Customer', {_ID}),
('column_return_id', 'language', 'Return ID', {_ID}),
('text_history', 'language', 'Add Return History', {_ID}),
('text_order', 'language', 'Order Information', {_ID}),
('text_product', 'language', 'Product Information &amp; Reason for Return', {_ID}),
('text_edit', 'language', 'Edit Product Return', {_ID}),
('text_opened', 'language', 'Opened', {_ID}),
('text_unopened', 'language', 'Unopened', {_ID}),
('text_add', 'language', 'Add Product Return', {_ID}),
('text_success', 'language', 'Success: You have modified returns!', {_ID}),
('text_list', 'language', 'Product Return List', {_ID}),
('heading_title', 'language', 'Product Returns', {_ID}),
('warning_template_content', 'language', 'Are you sure you want to change the template? This will clear all of the text inside the editor', {_ID}),
('entry_template', 'language', 'Template', {_ID}),
('entry_summary', 'language', 'Summary', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('tab_google', 'language', 'Google', {_ID}),
('tab_action', 'language', 'Action', {_ID}),
('tab_recurring', 'language', 'Recurring', {_ID}),
('tab_activity', 'language', 'Recent Activity', {_ID}),
('tab_online', 'language', 'People Online', {_ID}),
('tab_marketing', 'language', 'Marketing', {_ID}),
('tab_sale', 'language', 'Sales', {_ID}),
('tab_voucher', 'language', 'Vouchers', {_ID}),
('tab_transaction', 'language', 'Transactions', {_ID}),
('tab_total', 'language', 'Totals', {_ID}),
('tab_shipping', 'language', 'Shipping Details', {_ID}),
('tab_reward', 'language', 'Reward Points', {_ID}),
('tab_product', 'language', 'Products', {_ID}),
('tab_payment', 'language', 'Payment Details', {_ID}),
('tab_mail', 'language', 'Mail', {_ID}),
('tab_module', 'language', 'Module', {_ID}),
('tab_local', 'language', 'Local', {_ID}),
('tab_session', 'language', 'Session', {_ID}),
('tab_special', 'language', 'Special', {_ID}),
('tab_store', 'language', 'Store', {_ID}),
('tab_server', 'language', 'Server', {_ID}),
('tab_option', 'language', 'Option', {_ID}),
('tab_image', 'language', 'Image', {_ID}),
('tab_ip', 'language', 'IP Addresses', {_ID}),
('tab_links', 'language', 'Links', {_ID}),
('tab_log', 'language', 'Log', {_ID}),
('tab_ftp', 'language', 'FTP', {_ID}),
('tab_discount', 'language', 'Discount', {_ID}),
('tab_general', 'language', 'General', {_ID}),
('tab_history', 'language', 'History', {_ID}),
('tab_data', 'language', 'Data', {_ID}),
('tab_design', 'language', 'Design', {_ID}),
('tab_customer', 'language', 'Customer Details', {_ID}),
('tab_admin', 'language', 'Admin', {_ID}),
('tab_attribute', 'language', 'Attribute', {_ID}),
('tab_address', 'language', 'Address', {_ID}),
('tab_additional', 'language', 'Additional', {_ID}),
('button_order_recurring', 'language', 'View Recurring Order', {_ID}),
('button_order', 'language', 'View Order', {_ID}),
('button_category_add', 'language', 'Add Category', {_ID}),
('button_apply', 'language', 'Apply', {_ID}),
('button_currency', 'language', 'Refresh Currency Values', {_ID}),
('button_parent', 'language', 'Parent', {_ID}),
('button_folder', 'language', 'New Folder', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_install', 'language', 'Install', {_ID}),
('button_uninstall', 'language', 'Uninstall', {_ID}),
('button_login', 'language', 'Login into Store', {_ID}),
('button_unlock', 'language', 'Unlock Account', {_ID}),
('button_link', 'language', 'Link', {_ID}),
('button_ip_add', 'language', 'Add IP', {_ID}),
('button_credit_remove', 'language', 'Remove Credit', {_ID}),
('button_credit_add', 'language', 'Add Credit', {_ID}),
('button_commission_remove', 'language', 'Remove Commission', {_ID}),
('button_reward_remove', 'language', 'Remove Reward Points', {_ID}),
('button_commission_add', 'language', 'Add Commission', {_ID}),
('button_reward_add', 'language', 'Add Reward Points', {_ID}),
('button_generate', 'language', 'Generate', {_ID}),
('button_voucher_add', 'language', 'Add Voucher', {_ID}),
('button_reset', 'language', 'Reset', {_ID}),
('button_approve', 'language', 'Approve', {_ID}),
('button_link_add', 'language', 'Add Link', {_ID}),
('button_module_add', 'language', 'Add Module', {_ID}),
('button_route_add', 'language', 'Add Route', {_ID}),
('button_rule_add', 'language', 'Add Rule', {_ID}),
('button_transaction_add', 'language', 'Add Transaction', {_ID}),
('button_translation_add', 'language', 'Add Translation', {_ID}),
('button_translation', 'language', 'Load Default Translation', {_ID}),
('button_history_add', 'language', 'Add History', {_ID}),
('button_geo_zone_add', 'language', 'Add Geo Zone', {_ID}),
('button_image_add', 'language', 'Add Image', {_ID}),
('button_special_add', 'language', 'Add Special', {_ID}),
('button_discount_add', 'language', 'Add Discount', {_ID}),
('button_recurring_add', 'language', 'Add Recurring', {_ID}),
('button_option_value_add', 'language', 'Add Option Value', {_ID}),
('button_option_add', 'language', 'Add Option', {_ID}),
('button_filter_add', 'language', 'Add Filter', {_ID}),
('button_product_add', 'language', 'Add Product', {_ID}),
('button_custom_field_value_add', 'language', 'Add Custom Field', {_ID}),
('button_banner_add', 'language', 'Add Banner', {_ID}),
('button_attribute_add', 'language', 'Add Attribute', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_shipping_print', 'language', 'Print Shipping List', {_ID}),
('button_invoice_print', 'language', 'Print Invoice', {_ID}),
('button_upload', 'language', 'Upload', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_rebuild', 'language', 'Rebuild', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_import', 'language', 'Import', {_ID}),
('button_export', 'language', 'Export', {_ID}),
('button_refresh', 'language', 'Refresh', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_copy', 'language', 'Copy', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_send', 'language', 'Send', {_ID}),
('button_filter', 'language', 'Filter', {_ID}),
('button_disable', 'language', 'Disable', {_ID}),
('button_enable', 'language', 'Enable', {_ID}),
('button_close', 'language', 'Close', {_ID}),
('button_clear', 'language', 'Clear', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_save', 'language', 'Save', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cancel_recurring', 'language', 'Cancel Recurring Payments', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_confirm', 'language', 'Are you sure?', {_ID}),
('text_home', 'language', 'Home', {_ID}),
('button_add', 'language', 'Add New', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_close', 'language', 'Close', {_ID}),
('text_select_all', 'language', 'Select All', {_ID}),
('text_unselect_all', 'language', 'Unselect All', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_enabled', 'language', 'Enabled', {_ID}),
('text_disabled', 'language', 'Disabled', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('mail.text', 'auto', 'Return ID: 7\nReturn Date: 16/04/2017\n\nYour return has been updated to the following status:\nAwaiting Products\n\nThe comments for your return are:\n\nThe following items of your order 38 have been refunded.\n\nPlease reply to this email if you have any questions.', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store - Return Update 7', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('preheader_preview', 'auto', 'The comments for your return are: The following items of your order 38 have been refunded.', {_ID}),
('reason', 'auto', 'Received Wrong Item', {_ID}),
('return_link', 'auto', 'http://localhost/index.php?route=account/return/info&return_id=7', {_ID}),
('order_date_modified', 'auto', '2017-04-16 20:17:04', {_ID}),
('order_date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('order_accept_language', 'auto', 'en-GB,en-US;q=0.8,en;q=0.6', {_ID}),
('order_user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36', {_ID}),
('order_ip', 'auto', 'localhost', {_ID}),
('order_currency_value', 'auto', '1.00000000', {_ID}),
('order_language_code', 'auto', 'en-gb', {_ID}),
('order_currency_id', 'auto', '2', {_ID}),
('order_currency_code', 'auto', 'USD', {_ID}),
('order_commission', 'auto', '0.0000', {_ID}),
('order_language_id', 'auto', '1', {_ID}),
('order_affiliate_id', 'auto', '0', {_ID}),
('order_order_status', 'auto', 'Complete', {_ID}),
('order_order_status_id', 'auto', '5', {_ID}),
('order_reward', 'auto', '1400', {_ID}),
('order_total', 'auto', '964.0000', {_ID}),
('order_comment', 'auto', 'Test comment\n\nWith line break', {_ID}),
('order_shipping_code', 'auto', 'flat.flat', {_ID}),
('order_shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('order_shipping_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('order_shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('order_shipping_iso_code_2', 'auto', 'GB', {_ID}),
('order_shipping_country', 'auto', 'United Kingdom', {_ID}),
('order_shipping_country_id', 'auto', '222', {_ID}),
('order_shipping_zone_code', 'auto', 'LDN', {_ID}),
('order_shipping_zone', 'auto', 'Greater London', {_ID}),
('order_shipping_city', 'auto', 'London', {_ID}),
('order_shipping_zone_id', 'auto', '3553', {_ID}),
('order_shipping_postcode', 'auto', 'SW1A 0AA', {_ID}),
('order_shipping_address_2', 'auto', 'Westminster ', {_ID}),
('order_shipping_address_1', 'auto', '12 Long Lane', {_ID}),
('order_shipping_company', 'auto', 'Opencart-Templates', {_ID}),
('order_shipping_lastname', 'auto', 'Johnson', {_ID}),
('order_shipping_firstname', 'auto', 'Ben', {_ID}),
('order_payment_method', 'auto', 'Cash On Delivery', {_ID}),
('order_payment_code', 'auto', 'cod', {_ID}),
('order_payment_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('order_payment_iso_code_2', 'auto', 'GB', {_ID}),
('order_payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order_payment_country', 'auto', 'United Kingdom', {_ID}),
('order_payment_country_id', 'auto', '222', {_ID}),
('order_payment_zone_code', 'auto', 'LDN', {_ID}),
('order_payment_zone', 'auto', 'Greater London', {_ID}),
('order_payment_zone_id', 'auto', '3553', {_ID}),
('order_payment_city', 'auto', 'London', {_ID}),
('order_payment_postcode', 'auto', 'SW1A 0AA', {_ID}),
('order_payment_address_2', 'auto', 'Westminster ', {_ID}),
('order_payment_address_1', 'auto', '12 Long Lane', {_ID}),
('order_payment_company', 'auto', 'Opencart-Templates', {_ID}),
('order_payment_lastname', 'auto', 'Johnson', {_ID}),
('order_payment_firstname', 'auto', 'Ben', {_ID}),
('order_custom_field.1', 'auto', '123456', {_ID}),
('order_fax', 'auto', '0113456789', {_ID}),
('order_telephone', 'auto', '0123456789', {_ID}),
('order_email', 'auto', 'user@localhost', {_ID}),
('order_lastname', 'auto', 'Johnson', {_ID}),
('order_customer_group_id', 'auto', '1', {_ID}),
('order_firstname', 'auto', 'Ben', {_ID}),
('order_store_url', 'auto', 'http://localhost/', {_ID}),
('order_customer_id', 'auto', '23', {_ID}),
('order_store_name', 'auto', 'Your Store', {_ID}),
('order_store_id', 'auto', '0', {_ID}),
('order_invoice_prefix', 'auto', 'INV-2017-00', {_ID}),
('order_invoice_no', 'auto', '0', {_ID}),
('order_order_id', 'auto', '38', {_ID}),
('name', 'auto', 'Awaiting Products', {_ID}),
('status', 'auto', 'Awaiting Products', {_ID}),
('date_modified', 'auto', '2017-04-20 11:18:46', {_ID}),
('date_ordered', 'auto', '2017-04-16', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('return_action_id', 'auto', '0', {_ID}),
('return_status_id', 'auto', '2', {_ID}),
('comment', 'auto', 'The following items of your order 38 have been refunded.', {_ID}),
('opened', 'auto', 'No', {_ID}),
('return_reason_id', 'auto', '2', {_ID}),
('quantity', 'auto', '1', {_ID}),
('model', 'auto', 'product 20', {_ID}),
('product', 'auto', 'iPod Classic', {_ID}),
('telephone', 'auto', '0123456789', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('product_id', 'auto', '0', {_ID}),
('order_id', 'auto', '38', {_ID}),
('return_id', 'auto', '7', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_ssl', 'auto', 'http://localhost/', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '23', {_ID}),
('language_id', 'auto', '1', {_ID}),
('error_product', 'language', 'Product Name must be greater than 3 and less than 255 characters!', {_ID}),
('error_model', 'language', 'Product Model must be greater than 3 and less than 64 characters!', {_ID}),
('text_subject', 'language', '%s - Return Update %s', {_ID}),
('text_return_id', 'language', 'Return ID:', {_ID}),
('text_date_added', 'language', 'Return Date:', {_ID}),
('text_return_status', 'language', 'Your return has been updated to the following status:', {_ID}),
('text_comment', 'language', 'The comments for your return are:', {_ID}),
('text_footer', 'language', 'Please reply to this email if you have any questions.', {_ID}),
('text_heading', 'language', 'Return Update', {_ID}),
('text_return_link', 'language', 'View return details:', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_unsubscribe', 'language', '<a href=\"%s\">Unsubscribe</a> from our newsletter', {_ID})