INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '25', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('affiliate_id', 'auto', '1', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('telephone', 'auto', '01234556789', {_ID}),
('fax', 'auto', '1234556789', {_ID}),
('salt', 'auto', 'JHl0VRoiC', {_ID}),
('company', 'auto', 'opencart-templates', {_ID}),
('website', 'auto', 'http://www.opencart-templates.co.uk', {_ID}),
('address_1', 'auto', '1 long lane', {_ID}),
('address_2', 'auto', 'south district', {_ID}),
('city', 'auto', 'London', {_ID}),
('postcode', 'auto', 'L1234343', {_ID}),
('country_id', 'auto', '222', {_ID}),
('zone_id', 'auto', '3553', {_ID}),
('commission', 'auto', '5.00', {_ID}),
('tax', 'auto', '123', {_ID}),
('payment', 'auto', 'cheque', {_ID}),
('cheque', 'auto', 'Opencart Templates', {_ID}),
('status', 'auto', '1', {_ID}),
('approved', 'auto', '1', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('url_affiliate_login', 'auto', 'http://localhost/index.php?route=affiliate/login', {_ID}),
('text_affiliate', 'auto', 'Your account has now been created and you can log in by using your e-mail address and password by visiting our website or at the following URL:', {_ID}),
('preheader_preview', 'auto', 'Thank you for joining the %s Affiliate Program!', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store - Affiliate Program', {_ID}),
('mail.text', 'auto', 'Thank you for joining the Your Store Affiliate Program!\n\nYour account has now been created and you can log in by using your e-mail address and password by visiting our website or at the following URL:\nhttp://localhost/index.php?route=affiliate/login\n\nUpon logging in, you will be able to generate tracking codes, track commission payments and edit your account information.\n\nThanks,\nYour Store', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('heading_title', 'language', 'Affiliate Program', {_ID}),
('text_account', 'language', 'Account', {_ID}),
('text_register', 'language', 'Affiliate Register', {_ID}),
('text_account_already', 'language', 'If you already have an account with us, please login at the <a href=\"%s\">login page</a>.', {_ID}),
('text_signup', 'language', 'A new affiliate has signed up:', {_ID}),
('text_your_details', 'language', 'Your Personal Details', {_ID}),
('text_your_address', 'language', 'Your Address Details', {_ID}),
('text_payment', 'language', 'Payment Information', {_ID}),
('text_your_password', 'language', 'Your Password', {_ID}),
('text_cheque', 'language', 'Cheque', {_ID}),
('text_paypal', 'language', 'PayPal', {_ID}),
('text_bank', 'language', 'Bank Transfer', {_ID}),
('text_agree', 'language', 'I have read and agree to the <a href=\"%s\" class=\"agree\"><b>%s</b></a>', {_ID}),
('entry_firstname', 'language', 'First Name', {_ID}),
('entry_lastname', 'language', 'Last Name', {_ID}),
('entry_email', 'language', 'E-Mail', {_ID}),
('entry_telephone', 'language', 'Telephone', {_ID}),
('entry_fax', 'language', 'Fax', {_ID}),
('entry_company', 'language', 'Company', {_ID}),
('entry_website', 'language', 'Web Site', {_ID}),
('entry_address_1', 'language', 'Address 1', {_ID}),
('entry_address_2', 'language', 'Address 2', {_ID}),
('entry_postcode', 'language', 'Post Code', {_ID}),
('entry_city', 'language', 'City', {_ID}),
('entry_country', 'language', 'Country', {_ID}),
('entry_zone', 'language', 'Region / State', {_ID}),
('entry_tax', 'language', 'Tax ID', {_ID}),
('entry_payment', 'language', 'Payment Method', {_ID}),
('entry_cheque', 'language', 'Cheque Payee Name', {_ID}),
('entry_paypal', 'language', 'PayPal Email Account', {_ID}),
('entry_bank_name', 'language', 'Bank Name', {_ID}),
('entry_bank_branch_number', 'language', 'ABA/BSB number (Branch Number)', {_ID}),
('entry_bank_swift_code', 'language', 'SWIFT Code', {_ID}),
('entry_bank_account_name', 'language', 'Account Name', {_ID}),
('entry_bank_account_number', 'language', 'Account Number', {_ID}),
('entry_password', 'language', 'Password', {_ID}),
('entry_confirm', 'language', 'Password Confirm', {_ID}),
('error_exists', 'language', 'Warning: E-Mail Address is already registered!', {_ID}),
('error_firstname', 'language', 'First Name must be between 1 and 32 characters!', {_ID}),
('error_lastname', 'language', 'Last Name must be between 1 and 32 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_telephone', 'language', 'Telephone must be between 3 and 32 characters!', {_ID}),
('error_password', 'language', 'Password must be between 4 and 20 characters!', {_ID}),
('error_confirm', 'language', 'Password confirmation does not match password!', {_ID}),
('error_address_1', 'language', 'Address 1 must be between 3 and 128 characters!', {_ID}),
('error_city', 'language', 'City must be between 2 and 128 characters!', {_ID}),
('error_country', 'language', 'Please select a country!', {_ID}),
('error_zone', 'language', 'Please select a region / state!', {_ID}),
('error_postcode', 'language', 'Postcode must be between 2 and 10 characters!', {_ID}),
('error_agree', 'language', 'Warning: You must agree to the %s!', {_ID}),
('text_subject', 'language', '%s - Affiliate Program', {_ID}),
('text_welcome', 'language', 'Thank you for joining the %s Affiliate Program!', {_ID}),
('text_login', 'language', 'Your account has now been created and you can log in by using your e-mail address and password by visiting our website or at the following URL:', {_ID}),
('text_approval', 'language', 'Your account must be approved before you can login. Once approved you can log in by using your e-mail address and password by visiting our website or at the following URL:', {_ID}),
('text_services', 'language', 'Upon logging in, you will be able to generate tracking codes, track commission payments and edit your account information.', {_ID}),
('text_thanks', 'language', 'Thanks,', {_ID}),
('text_new_affiliate', 'language', 'New Affiliate', {_ID}),
('text_store', 'language', 'Store:', {_ID}),
('text_firstname', 'language', 'Firstname:', {_ID}),
('text_lastname', 'language', 'Lastname:', {_ID}),
('text_company', 'language', 'Company:', {_ID}),
('text_email', 'language', 'E-Mail:', {_ID}),
('text_telephone', 'language', 'Telephone:', {_ID}),
('text_website', 'language', 'Web Site:', {_ID}),
('text_order_id', 'language', 'Order ID:', {_ID}),
('text_transaction_subject', 'language', '%s - Affiliate Commission', {_ID}),
('text_transaction_received', 'language', 'You have received %s commission!', {_ID}),
('text_transaction_total', 'language', 'Your total amount of commission is now %s.', {_ID}),
('text_affiliate_subject', 'language', '{$store_name} - Affiliate Program', {_ID}),
('text_affiliate_welcome', 'language', 'Thank you for joining the {$store_name} Affiliate Program!', {_ID}),
('text_fax', 'language', 'Fax', {_ID}),
('text_name', 'language', 'Name', {_ID}),
('text_rating', 'language', 'Rating', {_ID});