INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '23', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('name', 'auto', 'Ben', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('enquiry', 'auto', 'Test message\r<br />\r<br />With line breaks', {_ID}),
('customer.customer_id', 'auto', '23', {_ID}),
('customer.customer_group_id', 'auto', '1', {_ID}),
('customer.store_id', 'auto', '0', {_ID}),
('customer.language_id', 'auto', '1', {_ID}),
('customer.firstname', 'auto', 'Ben', {_ID}),
('customer.lastname', 'auto', 'Johnson', {_ID}),
('customer.email', 'auto', 'user@localhost', {_ID}),
('customer.telephone', 'auto', '0123456789', {_ID}),
('customer.fax', 'auto', '0113456789', {_ID}),
('customer.salt', 'auto', 'LQXjRtkvr', {_ID}),
('customer.newsletter', 'auto', '1', {_ID}),
('customer.address_id', 'auto', '21', {_ID}),
('customer.custom_field', 'auto', '{\"1\":\"123456\"}', {_ID}),
('customer.ip', 'auto', 'localhost', {_ID}),
('customer.status', 'auto', '1', {_ID}),
('customer.approved', 'auto', '1', {_ID}),
('customer.safe', 'auto', '0', {_ID}),
('customer.code', 'auto', 'gI6eSKSQprQ3YXPKPeY8qL3YT3BdEAu766SxxEEW', {_ID}),
('customer.date_added', 'auto', '2017-04-16 20:13:04', {_ID}),
('preheader_preview', 'auto', 'Your Store Enquiry', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.reply_to', 'auto', 'store@localhost', {_ID}),
('mail.subject', 'auto', 'Copy of Your Store Enquiry', {_ID}),
('mail.text', 'auto', 'Test message\r\n\r\nWith line breaks', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('heading_title', 'language', 'Contact Us', {_ID}),
('text_location', 'language', 'Our Location', {_ID}),
('text_store', 'language', 'Our Stores', {_ID}),
('text_contact', 'language', 'Contact Form', {_ID}),
('text_address', 'language', 'Address', {_ID}),
('text_telephone', 'language', 'Telephone', {_ID}),
('text_fax', 'language', 'Fax', {_ID}),
('text_open', 'language', 'Opening Times', {_ID}),
('text_comment', 'language', 'Comments', {_ID}),
('text_success', 'language', '<p>Your enquiry has been successfully sent to the store owner!</p>', {_ID}),
('entry_name', 'language', 'Your Name', {_ID}),
('entry_email', 'language', 'E-Mail Address', {_ID}),
('entry_enquiry', 'language', 'Enquiry', {_ID}),
('email_subject', 'language', 'Enquiry %s', {_ID}),
('error_name', 'language', 'Name must be between 3 and 32 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_enquiry', 'language', 'Enquiry must be between 10 and 3000 characters!', {_ID}),
('text_subject', 'language', 'Enquiry from: {$name} at: {$store_name}', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_email', 'language', 'Email:', {_ID}),
('text_customer_subject', 'language', 'Copy of your {$store_name} Enquiry', {_ID}),
('text_customer_heading', 'language', '{$store_name} Enquiry', {_ID}),
('text_customer_enquiry', 'language', 'Thank you for your enquiry, here is a copy of your message:', {_ID}),
('text_rating', 'language', 'Rating', {_ID});