INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '0', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('review_name', 'auto', 'Ben', {_ID}),
('review_text', 'auto', 'Arrived on time and installation was a piece of cake.', {_ID}),
('review_rating', 'auto', '5', {_ID}),
('product_product_id', 'auto', '33', {_ID}),
('product_name', 'auto', 'Samsung SyncMaster 941BW', {_ID}),
('product_description', 'auto', '&lt;div&gt;\r\n	Imagine the advantages of going big without slowing down. The big 19&amp;quot; 941BW monitor combines wide aspect ratio with fast pixel response time, for bigger images, more room to work and crisp motion. In addition, the exclusive MagicBright 2, MagicColor and MagicTune technologies help deliver the ideal image in every situation, while sleek, narrow bezels and adjustable stands deliver style just the way you want it. With the Samsung 941BW widescreen analog/digital LCD monitor, it&amp;#39;s not hard to imagine.&lt;/div&gt;\r\n', {_ID}),
('product_meta_title', 'auto', 'Samsung SyncMaster 941BW', {_ID}),
('product_model', 'auto', 'Product 6', {_ID}),
('product_quantity', 'auto', '999', {_ID}),
('product_stock_status', 'auto', '2-3 Days', {_ID}),
('product_image', 'auto', 'catalog/demo/samsung_syncmaster_941bw.jpg', {_ID}),
('product_price', 'auto', '200.0000', {_ID}),
('product_reward', 'auto', '0', {_ID}),
('product_points', 'auto', '0', {_ID}),
('product_tax_class_id', 'auto', '9', {_ID}),
('product_date_available', 'auto', '2017-04-20 11:18:46', {_ID}),
('product_weight', 'auto', '5.00000000', {_ID}),
('product_weight_class_id', 'auto', '1', {_ID}),
('product_length', 'auto', '0.00000000', {_ID}),
('product_width', 'auto', '0.00000000', {_ID}),
('product_height', 'auto', '0.00000000', {_ID}),
('product_length_class_id', 'auto', '2', {_ID}),
('product_subtract', 'auto', '1', {_ID}),
('product_rating', 'auto', '0', {_ID}),
('product_reviews', 'auto', '0', {_ID}),
('product_minimum', 'auto', '1', {_ID}),
('product_sort_order', 'auto', '0', {_ID}),
('product_status', 'auto', '1', {_ID}),
('product_date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('product_date_modified', 'auto', '2017-04-20 11:18:46', {_ID}),
('product_viewed', 'auto', '2', {_ID}),
('review_approve', 'auto', 'https://localhost/admin/index.php?route=catalog/review/edit&review_id=2', {_ID}),
('customer_link', 'auto', 'https://localhost/admin/index.php?route=customer/customer&filter_name=Ben', {_ID}),
('product_link', 'auto', 'http://localhost/index.php?route=product/product&amp;product_id=33', {_ID}),
('preheader_preview', 'auto', 'New review awaiting approval for: %s', {_ID}),
('mail.to', 'auto', 'store@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Ben', {_ID}),
('mail.subject', 'auto', 'Your Store - Product Review', {_ID}),
('mail.text', 'auto', 'You have a new product review waiting.\nProduct: Samsung SyncMaster 941BW\nReviewer: Ben\nRating: 5\nReview Text:\nArrived on time and installation was a piece of cake.\n\n', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('text_search', 'language', 'Search', {_ID}),
('text_brand', 'language', 'Brand', {_ID}),
('text_manufacturer', 'language', 'Brand:', {_ID}),
('text_model', 'language', 'Product Code:', {_ID}),
('text_reward', 'language', 'Reward Points:', {_ID}),
('text_points', 'language', 'Price in reward points:', {_ID}),
('text_stock', 'language', 'Availability:', {_ID}),
('text_instock', 'language', 'In Stock', {_ID}),
('text_tax', 'language', 'Ex Tax:', {_ID}),
('text_discount', 'language', ' or more ', {_ID}),
('text_option', 'language', 'Available Options', {_ID}),
('text_minimum', 'language', 'This product has a minimum quantity of %s', {_ID}),
('text_reviews', 'language', '%s reviews', {_ID}),
('text_write', 'language', 'Write a review', {_ID}),
('text_login', 'language', 'Please <a href=\"%s\">login</a> or <a href=\"%s\">register</a> to review', {_ID}),
('text_no_reviews', 'language', 'There are no reviews for this product.', {_ID}),
('text_note', 'language', '<span class=\"text-danger\">Note:</span> HTML is not translated!', {_ID}),
('text_success', 'language', 'Thank you for your review. It has been submitted to the webmaster for approval.', {_ID}),
('text_related', 'language', 'Related Products', {_ID}),
('text_tags', 'language', 'Tags:', {_ID}),
('text_error', 'language', 'Product not found!', {_ID}),
('text_payment_recurring', 'language', 'Payment Profile', {_ID}),
('text_trial_description', 'language', '%s every %d %s(s) for %d payment(s) then', {_ID}),
('text_payment_description', 'language', '%s every %d %s(s) for %d payment(s)', {_ID}),
('text_payment_cancel', 'language', '%s every %d %s(s) until canceled', {_ID}),
('text_day', 'language', 'day', {_ID}),
('text_week', 'language', 'week', {_ID}),
('text_semi_month', 'language', 'half-month', {_ID}),
('text_month', 'language', 'month', {_ID}),
('text_year', 'language', 'year', {_ID}),
('entry_qty', 'language', 'Qty', {_ID}),
('entry_name', 'language', 'Your Name', {_ID}),
('entry_review', 'language', 'Your Review', {_ID}),
('entry_rating', 'language', 'Rating', {_ID}),
('entry_good', 'language', 'Good', {_ID}),
('entry_bad', 'language', 'Bad', {_ID}),
('tab_description', 'language', 'Description', {_ID}),
('tab_attribute', 'language', 'Specification', {_ID}),
('tab_review', 'language', 'Reviews (%s)', {_ID}),
('error_name', 'language', 'Warning: Review Name must be between 3 and 25 characters!', {_ID}),
('error_text', 'language', 'Warning: Review Text must be between 25 and 1000 characters!', {_ID}),
('error_rating', 'language', 'Warning: Please select a review rating!', {_ID}),
('text_subject', 'language', '%s - Product Review', {_ID}),
('text_waiting', 'language', 'You have a new product review waiting.', {_ID}),
('text_product', 'language', 'Product: %s', {_ID}),
('text_reviewer', 'language', 'Reviewer: %s', {_ID}),
('text_rating', 'language', 'Rating', {_ID}),
('text_review', 'language', 'Review Text:', {_ID}),
('text_review_approve', 'language', 'To approve review click on the link below', {_ID}),
('text_review_heading', 'language', 'New review awaiting approval for: %s', {_ID}),
('text_review_message', 'language', 'Message:', {_ID}),
('text_review_product', 'language', 'Product:', {_ID}),
('text_review_rating', 'language', 'Rating:', {_ID}),
('text_review_review', 'language', 'You have received a new review for', {_ID}),
('text_review_reviewer', 'language', 'Reviewer:', {_ID});