INSERT INTO `oc_emailtemplate` SET
`emailtemplate_key` = 'customer.register_admin',
`emailtemplate_label` = 'Customer Register Admin',
`emailtemplate_type` = 'admin',
`emailtemplate_template` = 'customer_register_admin.tpl',
`emailtemplate_mail_to` = '{$store_email}',
`emailtemplate_mail_cc` = '',
`emailtemplate_mail_bcc` = '',
`emailtemplate_mail_from` = '{$email}',
`emailtemplate_mail_html` = 1,
`emailtemplate_mail_plain_text` = 1,
`emailtemplate_mail_sender` = '{$firstname} {$lastname}',
`emailtemplate_mail_replyto` = '',
`emailtemplate_mail_replyto_name` = '',
`emailtemplate_mail_attachment` = '',
`emailtemplate_attach_invoice` = 0,
`emailtemplate_language_files` = 'extension/mail/customer',
`emailtemplate_wrapper_tpl` = '',
`emailtemplate_status` = 1,
`emailtemplate_default` = 1,
`emailtemplate_shortcodes` = 0,
`emailtemplate_showcase` = 0,
`emailtemplate_condition` = '',
`emailtemplate_modified` = NOW(),
`emailtemplate_log` = 0,
`emailtemplate_view_browser` = 0,
`emailtemplate_config_id` = 0,
`store_id` = NULL,
`customer_group_id` = 0,
`order_status_id` = 0,
`event_id` = '';

INSERT INTO `oc_emailtemplate_description` SET 
`emailtemplate_id` = {_ID},
`language_id` = 0,
`emailtemplate_description_subject` = '{$text_register_subject_admin}',
`emailtemplate_description_preview` = '',
`emailtemplate_description_content1` = '&lt;strong&gt;{$text_name}&lt;/strong&gt; {$firstname} {$lastname}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_email}&lt;/strong&gt; &lt;a href=&quot;mailto:{$email}&quot;&gt;{$email}&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_company}&lt;/strong&gt; {$company}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_telephone}&lt;/strong&gt; {$telephone}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_fax}&lt;/strong&gt; {$fax}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_address}&lt;/strong&gt;&lt;br&gt;{$address}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_newsletter}&lt;/strong&gt; {$newsletter}',
`emailtemplate_description_content2` = '',
`emailtemplate_description_content3` = '',
`emailtemplate_description_comment` = '',
`emailtemplate_description_unsubscribe_text` = '';