INSERT INTO `oc_emailtemplate` SET
`emailtemplate_key` = 'information.contact',
`emailtemplate_label` = 'Contact Us',
`emailtemplate_type` = 'admin',
`emailtemplate_template` = '',
`emailtemplate_mail_to` = '',
`emailtemplate_mail_cc` = '',
`emailtemplate_mail_bcc` = '',
`emailtemplate_mail_from` = '',
`emailtemplate_mail_html` = 1,
`emailtemplate_mail_plain_text` = 0,
`emailtemplate_mail_sender` = '',
`emailtemplate_mail_replyto` = '',
`emailtemplate_mail_replyto_name` = '',
`emailtemplate_mail_attachment` = '',
`emailtemplate_attach_invoice` = 0,
`emailtemplate_language_files` = 'extension/mail/contact',
`emailtemplate_wrapper_tpl` = '',
`emailtemplate_status` = 1,
`emailtemplate_default` = 1,
`emailtemplate_shortcodes` = 0,
`emailtemplate_showcase` = 0,
`emailtemplate_condition` = '',
`emailtemplate_modified` = NOW(),
`emailtemplate_log` = 0,
`emailtemplate_view_browser` = 0,
`emailtemplate_config_id` = 0,
`store_id` = NULL,
`customer_group_id` = 0,
`order_status_id` = 0,
`event_id` = '';

INSERT INTO `oc_emailtemplate_description` SET 
`emailtemplate_id` = {_ID},
`language_id` = 0,
`emailtemplate_description_subject` = '{$text_subject}',
`emailtemplate_description_preview` = '',
`emailtemplate_description_content1` = '&lt;strong&gt;{$text_name}&lt;/strong&gt; {$name}&lt;br&gt;&lt;br&gt;&lt;strong&gt;{$text_email}&lt;/strong&gt; {$email}&lt;br&gt;&lt;br&gt;&lt;table class=&quot;tableInfo&quot; cellpadding=&quot;5&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;	&lt;tbody&gt;		&lt;tr&gt;			&lt;td bgcolor=&quot;#f6f6f6&quot;&gt;{$enquiry}&lt;/td&gt;		&lt;/tr&gt;	&lt;/tbody&gt;&lt;/table&gt;',
`emailtemplate_description_content2` = '',
`emailtemplate_description_content3` = '',
`emailtemplate_description_comment` = '',
`emailtemplate_description_unsubscribe_text` = '';