INSERT INTO `oc_emailtemplate` SET
`emailtemplate_key` = 'product.review',
`emailtemplate_label` = 'Product Review Notice',
`emailtemplate_type` = 'admin',
`emailtemplate_template` = '',
`emailtemplate_mail_to` = '{$store_email}',
`emailtemplate_mail_cc` = '',
`emailtemplate_mail_bcc` = '',
`emailtemplate_mail_from` = '{$store_email}',
`emailtemplate_mail_html` = 1,
`emailtemplate_mail_plain_text` = 0,
`emailtemplate_mail_sender` = '{$review_name}',
`emailtemplate_mail_replyto` = '',
`emailtemplate_mail_replyto_name` = '',
`emailtemplate_mail_attachment` = '',
`emailtemplate_attach_invoice` = 0,
`emailtemplate_language_files` = 'extension/mail/review',
`emailtemplate_wrapper_tpl` = '',
`emailtemplate_status` = 1,
`emailtemplate_default` = 1,
`emailtemplate_shortcodes` = 0,
`emailtemplate_showcase` = 0,
`emailtemplate_condition` = '',
`emailtemplate_modified` = NOW(),
`emailtemplate_log` = 0,
`emailtemplate_view_browser` = 0,
`emailtemplate_config_id` = 0,
`store_id` = NULL,
`customer_group_id` = 0,
`order_status_id` = 0,
`event_id` = '';

INSERT INTO `oc_emailtemplate_description` SET 
`emailtemplate_id` = {_ID},
`language_id` = 0,
`emailtemplate_description_subject` = '',
`emailtemplate_description_preview` = '{$text_review_heading}',
`emailtemplate_description_content1` = '&lt;div style=&quot;padding-top:4px;padding-bottom:4px;&quot;&gt;\r\n	&lt;b&gt;{$text_review_product}&lt;/b&gt; &lt;a href=&quot;{$product_link}&quot; target=&quot;_blank&quot;&gt;{$product_name}&lt;/a&gt;\r\n&lt;/div&gt;&lt;br&gt;\r\n&lt;div style=&quot;padding-top:4px;padding-bottom:4px;&quot;&gt;\r\n	&lt;b&gt;{$text_review_reviewer}&lt;/b&gt; &lt;a href=&quot;{$customer_link}&quot; target=&quot;_blank&quot;&gt;{$review_name}&lt;/a&gt;\r\n&lt;/div&gt;&lt;br&gt;\r\n&lt;strong&gt;{$text_review_rating} &lt;/strong&gt; {$review_rating}&lt;br&gt;\r\n&lt;br&gt;\r\n&lt;strong&gt;{$text_review_message} &lt;/strong&gt; {$review_text}&lt;br&gt;&lt;br&gt;\r\n\r\n&lt;div class=&quot;link last&quot;&gt;\r\n	{$text_review_approve}&lt;br&gt;\r\n&lt;a href=&quot;{$review_approve}&quot; target=&quot;_blank&quot;&gt;&lt;b&gt;{$review_approve}&lt;/b&gt; &lt;/a&gt;\r\n&lt;/div&gt;',
`emailtemplate_description_content2` = '',
`emailtemplate_description_content3` = '',
`emailtemplate_description_comment` = '',
`emailtemplate_description_unsubscribe_text` = '';