INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '25', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('affiliate.affiliate_id', 'auto', '1', {_ID}),
('affiliate.firstname', 'auto', 'Ben', {_ID}),
('affiliate.lastname', 'auto', 'Johnson', {_ID}),
('affiliate.email', 'auto', 'user@localhost', {_ID}),
('affiliate.telephone', 'auto', '01234556789', {_ID}),
('affiliate.fax', 'auto', '1234556789', {_ID}),
('affiliate.password', 'auto', 'c00855ad0d8b725cb0699a66ff16190f806527fd', {_ID}),
('affiliate.salt', 'auto', 'u9nUxQ0FI', {_ID}),
('affiliate.company', 'auto', 'opencart-templates', {_ID}),
('affiliate.website', 'auto', 'http://www.opencart-templates.co.uk', {_ID}),
('affiliate.address_1', 'auto', '1 long lane', {_ID}),
('affiliate.address_2', 'auto', 'south district', {_ID}),
('affiliate.city', 'auto', 'London', {_ID}),
('affiliate.postcode', 'auto', 'L1234343', {_ID}),
('affiliate.country_id', 'auto', '222', {_ID}),
('affiliate.zone_id', 'auto', '3553', {_ID}),
('affiliate.code', 'auto', '58f88701d68e9', {_ID}),
('affiliate.commission', 'auto', '5.00', {_ID}),
('affiliate.tax', 'auto', '123', {_ID}),
('affiliate.payment', 'auto', 'cheque', {_ID}),
('affiliate.cheque', 'auto', 'Opencart Templates', {_ID}),
('affiliate.ip', 'auto', 'localhost', {_ID}),
('affiliate.status', 'auto', '1', {_ID}),
('affiliate.approved', 'auto', '1', {_ID}),
('affiliate.date_added', 'auto', '2017-04-20 11:01:37', {_ID}),
('account_login', 'auto', 'http://localhost/index.php?route=affiliate/login', {_ID}),
('preheader_preview', 'auto', 'Log in by visiting:', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store - Forgotten Password', {_ID}),
('mail.text', 'auto', 'A new password was requested for Your Store customer account.\n\ntext_password\n\n0ewa6dUtxf', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('heading_title', 'language', 'Forgot Your Password?', {_ID}),
('text_account', 'language', 'Account', {_ID}),
('text_forgotten', 'language', 'Forgotten Password', {_ID}),
('text_your_email', 'language', 'Your E-Mail Address', {_ID}),
('text_email', 'language', 'Enter the e-mail address associated with your account. Click submit to have your password e-mailed to you', {_ID}),
('text_success', 'language', 'Success: A new password has been sent to your e-mail address.', {_ID}),
('entry_email', 'language', 'E-Mail Address', {_ID}),
('error_email', 'language', 'Warning: The E-Mail Address was not found in our records, please try again!', {_ID}),
('error_approved', 'language', 'Warning: Your account requires approval before you can login.', {_ID}),
('text_subject', 'language', '%s - Password reset request', {_ID}),
('text_greeting', 'language', 'A new password was requested for %s customer account.', {_ID}),
('text_change', 'language', 'To reset your password click on the link below:', {_ID}),
('text_ip', 'language', 'The IP used to make this request was: %s', {_ID}),
('text_affiliate_subject', 'language', '{$store_name} - Forgotten Password', {_ID}),
('text_customer_subject', 'language', '{$store_name} - Forgotten Password', {_ID}),
('text_heading', 'language', 'Forgotten Password', {_ID}),
('text_login', 'language', 'Log in by visiting:', {_ID}),
('text_new_password', 'language', 'Your new password is:', {_ID}),
('text_rating', 'language', 'Rating', {_ID})