INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('text_rating', 'language', 'Rating', {_ID}),
('text_telephone', 'language', 'Telephone:', {_ID}),
('text_lastname', 'language', 'Last Name:', {_ID}),
('text_website', 'language', 'Web Site:', {_ID}),
('text_firstname', 'language', 'First Name:', {_ID}),
('text_signup', 'language', 'A new customer has signed up:', {_ID}),
('text_thanks', 'language', 'Thanks,', {_ID}),
('text_new_customer', 'language', 'New customer', {_ID}),
('text_services', 'language', 'Upon logging in, you will be able to access other services including reviewing past orders, printing invoices and editing your account information.', {_ID}),
('text_approval', 'language', 'Your account must be approved before you can login. Once approved you can log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('text_login', 'language', 'Your account has now been created and you can log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('text_welcome', 'language', 'Welcome and thank you for registering at %s!', {_ID}),
('text_subject', 'language', '%s - Thank you for registering', {_ID}),
('text_register_subject_admin', 'language', 'New customer at: {$store_name}', {_ID}),
('text_register_approve_subject_admin', 'language', 'New customer requires approval at: {$store_name}', {_ID}),
('text_register_heading', 'language', 'Welcome to: {$store_name}!', {_ID}),
('text_register_subject', 'language', '{$store_name} - Thank you for registering', {_ID}),
('text_password', 'language', 'Password:', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_fax', 'language', 'Fax:', {_ID}),
('text_email', 'language', 'E-Mail:', {_ID}),
('text_customer_link', 'language', 'Edit Customer:', {_ID}),
('text_customer_approve', 'language', 'Customer requires approval!', {_ID}),
('text_company', 'language', 'Company:', {_ID}),
('text_customer_group', 'language', 'Customer Group:', {_ID}),
('text_address', 'language', 'Address:', {_ID}),
('error_agree', 'language', 'Warning: You must agree to the %s!', {_ID}),
('error_confirm', 'language', 'Password confirmation does not match password!', {_ID}),
('error_custom_field', 'language', '%s required!', {_ID}),
('error_password', 'language', 'Password must be between 4 and 20 characters!', {_ID}),
('error_zone', 'language', 'Please select a region / state!', {_ID}),
('error_country', 'language', 'Please select a country!', {_ID}),
('error_postcode', 'language', 'Postcode must be between 2 and 10 characters!', {_ID}),
('error_city', 'language', 'City must be between 2 and 128 characters!', {_ID}),
('error_address_1', 'language', 'Address 1 must be between 3 and 128 characters!', {_ID}),
('error_telephone', 'language', 'Telephone must be between 3 and 32 characters!', {_ID}),
('error_lastname', 'language', 'Last Name must be between 1 and 32 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_firstname', 'language', 'First Name must be between 1 and 32 characters!', {_ID}),
('entry_newsletter', 'language', 'Subscribe', {_ID}),
('entry_password', 'language', 'Password', {_ID}),
('entry_confirm', 'language', 'Password Confirm', {_ID}),
('error_exists', 'language', 'Warning: E-Mail Address is already registered!', {_ID}),
('entry_zone', 'language', 'Region / State', {_ID}),
('entry_city', 'language', 'City', {_ID}),
('entry_country', 'language', 'Country', {_ID}),
('entry_postcode', 'language', 'Post Code', {_ID}),
('entry_address_2', 'language', 'Address 2', {_ID}),
('entry_address_1', 'language', 'Address 1', {_ID}),
('entry_company', 'language', 'Company', {_ID}),
('entry_fax', 'language', 'Fax', {_ID}),
('entry_email', 'language', 'E-Mail', {_ID}),
('entry_telephone', 'language', 'Telephone', {_ID}),
('entry_lastname', 'language', 'Last Name', {_ID}),
('entry_firstname', 'language', 'First Name', {_ID}),
('entry_customer_group', 'language', 'Customer Group', {_ID}),
('text_agree', 'language', 'I have read and agree to the <a href=\"%s\" class=\"agree\"><b>%s</b></a>', {_ID}),
('text_your_password', 'language', 'Your Password', {_ID}),
('text_your_address', 'language', 'Your Address', {_ID}),
('text_newsletter', 'language', 'Newsletter:', {_ID}),
('text_your_details', 'language', 'Your Personal Details', {_ID}),
('text_account_already', 'language', 'If you already have an account with us, please login at the <a href=\"%s\">login page</a>.', {_ID}),
('text_account', 'language', 'Account', {_ID}),
('text_register', 'language', 'Register', {_ID}),
('heading_title', 'language', 'Register Account', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('mail.sender', 'auto', 'Your Store', {_ID}),
('mail.subject', 'auto', 'Your Store - Thank you for registering', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('code', 'language', 'en', {_ID}),
('mail.text', 'auto', 'Welcome and thank you for registering at Your Store!\n\nYour account has now been created and you can log in by using your email address and password by visiting our website or at the following URL:\nhttp://localhost/index.php?route=account/login\n\nUpon logging in, you will be able to access other services including reviewing past orders, printing invoices and editing your account information.\n\nThanks,\nYour Store', {_ID}),
('mail.to', 'auto', 'user@localhost', {_ID}),
('mail.from', 'auto', 'store@localhost', {_ID}),
('address_country', 'auto', 'United Kingdom', {_ID}),
('preheader_preview', 'auto', 'Your account has now been created and you can log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('address_zone', 'auto', 'Greater London', {_ID}),
('address', 'auto', 'Ben Johnson<br />Opencart Templates<br />1 long lane<br />south district<br />London L1 3ED<br />Greater London<br />United Kingdom', {_ID}),
('customer_group', 'auto', 'Default', {_ID}),
('customer_text', 'auto', 'Your account has now been created and you can log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('account_login', 'auto', 'http://localhost/index.php?route=account/login', {_ID}),
('custom_field_account_1_name', 'auto', 'VAT No', {_ID}),
('custom_field_account_1_value', 'auto', '123456', {_ID}),
('custom_field_address_2_value', 'auto', 'Opencart', {_ID}),
('custom_field_address_2_name', 'auto', 'testing', {_ID}),
('agree', 'auto', '1', {_ID}),
('newsletter', 'auto', 'No', {_ID}),
('confirm', 'auto', 'password', {_ID}),
('zone_id', 'auto', '3553', {_ID}),
('country_id', 'auto', '222', {_ID}),
('postcode', 'auto', 'L1 3ED', {_ID}),
('city', 'auto', 'London', {_ID}),
('address_2', 'auto', 'south district', {_ID}),
('telephone', 'auto', '1234556789', {_ID}),
('fax', 'auto', '0234556789', {_ID}),
('company', 'auto', 'Opencart Templates', {_ID}),
('address_1', 'auto', '1 long lane', {_ID}),
('custom_field', 'auto_serialize', 'YToyOntzOjc6ImFjY291bnQiO2E6MTp7aToxO3M6NjoiMTIzNDU2Ijt9czo3OiJhZGRyZXNzIjthOjE6e2k6MjtzOjg6Ik9wZW5jYXJ0Ijt9fQ==', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '25', {_ID}),
('language_id', 'auto', '1', {_ID}),
('store_id', 'auto', '0', {_ID});