INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('title', 'auto', 'Your Store', {_ID}),
('text_greeting', 'auto', 'Congratulations, You have received a Gift Certificate worth £25.00', {_ID}),
('text_from', 'auto', 'This Gift Certificate has been sent to you by Jeffery Zeldmand', {_ID}),
('text_message', 'auto', 'With a message saying', {_ID}),
('text_redeem', 'auto', 'To redeem this Gift Certificate, write down the redemption code which is <b>cdSackRfIE</b> then click on the the link below and purchase the product you wish to use this gift voucher on. You can enter the gift voucher code on the shopping cart page before you click checkout.', {_ID}),
('text_footer', 'auto', 'Please reply to this e-mail if you have any questions.', {_ID}),
('image', 'auto', 'http://www.opencart-templates.co.uk/image/catalog/demo/apple_logo.jpg', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://www.opencart-templates.co.uk/', {_ID}),
('message', 'auto', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br />\r\n', {_ID}),
('store_ssl', 'auto', 'http://www.opencart-templates.co.uk/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'jeffery@opencart-templates.co.uk', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_fax', 'auto', '999888777', {_ID}),
('store_country_id', 'auto', '123', {_ID}),
('store_zone_id', 'auto', '1913', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID});