INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '23', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_name', 'auto', 'Your Store', {_ID}),
('store_url', 'auto', 'http://localhost/index.php?route=common/home', {_ID}),
('store_ssl', 'auto', 'https://localhost/', {_ID}),
('store_owner', 'auto', 'Your Name', {_ID}),
('store_address', 'auto', 'Address 1', {_ID}),
('store_email', 'auto', 'store@localhost', {_ID}),
('store_telephone', 'auto', '123456789', {_ID}),
('store_country_id', 'auto', '222', {_ID}),
('store_currency', 'auto', 'USD', {_ID}),
('store_zone_id', 'auto', '3563', {_ID}),
('store_tax', 'auto', '1', {_ID}),
('store_tax_default', 'auto', 'shipping', {_ID}),
('store_customer_price', 'auto', '0', {_ID}),
('title', 'auto', 'Your Store', {_ID}),
('account_url', 'auto', 'http://localhost/index.php?route=account/account', {_ID}),
('contact_url', 'auto', 'http://localhost/index.php?route=information/contact', {_ID}),
('wrapper_tpl', 'auto', '_main.tpl', {_ID}),
('order_order_id', 'auto', '38', {_ID}),
('order_invoice_prefix', 'auto', 'INV-2017-00', {_ID}),
('order_store_id', 'auto', '0', {_ID}),
('order_store_name', 'auto', 'Your Store', {_ID}),
('order_store_url', 'auto', 'http://localhost/', {_ID}),
('order_customer_id', 'auto', '23', {_ID}),
('order_affiliate_id', 'auto', '0', {_ID}),
('order_customer_group_id', 'auto', '1', {_ID}),
('order_weight', 'auto', '0.00000000', {_ID}),
('order_firstname', 'auto', 'Ben', {_ID}),
('order_lastname', 'auto', 'Johnson', {_ID}),
('order_email', 'auto', 'user@localhost', {_ID}),
('order_telephone', 'auto', '0123456789', {_ID}),
('order_fax', 'auto', '0113456789', {_ID}),
('order_custom_field.1', 'auto', '123456', {_ID}),
('order_payment_firstname', 'auto', 'Ben', {_ID}),
('order_payment_lastname', 'auto', 'Johnson', {_ID}),
('order_payment_company', 'auto', 'Opencart-Templates', {_ID}),
('order_payment_address_1', 'auto', '12 Long Lane', {_ID}),
('order_payment_address_2', 'auto', 'Westminster ', {_ID}),
('order_payment_postcode', 'auto', 'SW1A 0AA', {_ID}),
('order_payment_city', 'auto', 'London', {_ID}),
('order_payment_zone_id', 'auto', '3553', {_ID}),
('order_payment_zone', 'auto', 'Greater London', {_ID}),
('order_payment_zone_code', 'auto', 'LDN', {_ID}),
('order_payment_country_id', 'auto', '222', {_ID}),
('order_payment_country', 'auto', 'United Kingdom', {_ID}),
('order_payment_iso_code_2', 'auto', 'GB', {_ID}),
('order_payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order_payment_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('order_payment_method', 'auto', 'Cash On Delivery', {_ID}),
('order_payment_code', 'auto', 'cod', {_ID}),
('order_shipping_firstname', 'auto', 'Ben', {_ID}),
('order_shipping_lastname', 'auto', 'Johnson', {_ID}),
('order_shipping_company', 'auto', 'Opencart-Templates', {_ID}),
('order_shipping_address_1', 'auto', '12 Long Lane', {_ID}),
('order_shipping_address_2', 'auto', 'Westminster ', {_ID}),
('order_shipping_postcode', 'auto', 'SW1A 0AA', {_ID}),
('order_shipping_city', 'auto', 'London', {_ID}),
('order_shipping_zone_id', 'auto', '3553', {_ID}),
('order_shipping_zone', 'auto', 'Greater London', {_ID}),
('order_shipping_zone_code', 'auto', 'LDN', {_ID}),
('order_shipping_country_id', 'auto', '222', {_ID}),
('order_shipping_country', 'auto', 'United Kingdom', {_ID}),
('order_shipping_iso_code_2', 'auto', 'GB', {_ID}),
('order_shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('order_shipping_custom_field.2', 'auto', 'Testing custom field', {_ID}),
('order_shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('order_shipping_code', 'auto', 'flat.flat', {_ID}),
('order_comment', 'auto', 'Test comment\n\nWith line break', {_ID}),
('order_total', 'auto', '$964.00', {_ID}),
('order_order_status_id', 'auto', '5', {_ID}),
('order_order_status', 'auto', 'Complete', {_ID}),
('order_commission', 'auto', '0.0000', {_ID}),
('order_language_id', 'auto', '1', {_ID}),
('order_language_code', 'auto', 'en-gb', {_ID}),
('order_currency_id', 'auto', '2', {_ID}),
('order_currency_code', 'auto', 'USD', {_ID}),
('order_currency_value', 'auto', '1.00000000', {_ID}),
('order_ip', 'auto', 'localhost', {_ID}),
('order_user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36', {_ID}),
('order_accept_language', 'auto', 'en-GB,en-US;q=0.8,en;q=0.6', {_ID}),
('order_date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('order_date_modified', 'auto', '2017-04-16 20:17:04', {_ID}),
('order_date', 'auto', '16/04/2017', {_ID}),
('return_id', 'auto', '7', {_ID}),
('order_id', 'auto', '38', {_ID}),
('firstname', 'auto', 'Ben', {_ID}),
('lastname', 'auto', 'Johnson', {_ID}),
('email', 'auto', 'user@localhost', {_ID}),
('telephone', 'auto', '0123456789', {_ID}),
('product', 'auto', 'iPod Classic', {_ID}),
('model', 'auto', 'product 20', {_ID}),
('quantity', 'auto', '1', {_ID}),
('opened', 'auto', 'No', {_ID}),
('reason', 'auto', 'Received Wrong Item', {_ID}),
('status', 'auto', 'Awaiting Products', {_ID}),
('comment', 'auto', 'Wrong color', {_ID}),
('date_ordered', 'auto', '2017-04-16', {_ID}),
('date_added', 'auto', '2017-04-20 11:18:46', {_ID}),
('date_modified', 'auto', '2017-04-20 11:18:46', {_ID}),
('order_payment_address', 'auto', 'Ben Johnson<br />Opencart-Templates<br />12 Long Lane<br />Westminster<br />London SW1A 0AA<br />Greater London<br />United Kingdom', {_ID}),
('order_shipping_address', 'auto', 'Ben Johnson<br />Opencart-Templates<br />12 Long Lane<br />Westminster<br />London SW1A 0AA<br />Greater London<br />United Kingdom', {_ID}),
('return_date', 'auto', '16/04/2017', {_ID}),
('return_link', 'auto', 'https://localhost/admin/index.php?route=sale/return/info&return_id=7', {_ID}),
('mail.to', 'auto', 'store@localhost', {_ID}),
('mail.from', 'auto', 'user@localhost', {_ID}),
('mail.sender', 'auto', 'Ben Johnson', {_ID}),
('mail.subject', 'auto', 'New return for: Your Store', {_ID}),
('code', 'language', 'en', {_ID}),
('direction', 'language', 'ltr', {_ID}),
('date_format_short', 'language', 'd/m/Y', {_ID}),
('date_format_long', 'language', 'l dS F Y', {_ID}),
('time_format', 'language', 'h:i:s A', {_ID}),
('datetime_format', 'language', 'd/m/Y H:i:s', {_ID}),
('text_home', 'language', '<i class=\"fa fa-home\"></i>', {_ID}),
('text_yes', 'language', 'Yes', {_ID}),
('text_no', 'language', 'No', {_ID}),
('text_all_zones', 'language', 'All Zones', {_ID}),
('text_pagination', 'language', 'Showing %d to %d of %d (%d Pages)', {_ID}),
('text_no_results', 'language', 'No results!', {_ID}),
('button_address_add', 'language', 'Add Address', {_ID}),
('button_back', 'language', 'Back', {_ID}),
('button_continue', 'language', 'Continue', {_ID}),
('button_cart', 'language', 'Add to Cart', {_ID}),
('button_cancel', 'language', 'Cancel', {_ID}),
('button_compare', 'language', 'Compare this Product', {_ID}),
('button_wishlist', 'language', 'Add to Wish List', {_ID}),
('button_checkout', 'language', 'Checkout', {_ID}),
('button_confirm', 'language', 'Confirm Order', {_ID}),
('button_coupon', 'language', 'Apply Coupon', {_ID}),
('button_delete', 'language', 'Delete', {_ID}),
('button_download', 'language', 'Download', {_ID}),
('button_edit', 'language', 'Edit', {_ID}),
('button_filter', 'language', 'Refine Search', {_ID}),
('button_new_address', 'language', 'New Address', {_ID}),
('button_change_address', 'language', 'Change Address', {_ID}),
('button_reviews', 'language', 'Reviews', {_ID}),
('button_write', 'language', 'Write Review', {_ID}),
('button_login', 'language', 'Login', {_ID}),
('button_update', 'language', 'Update', {_ID}),
('button_remove', 'language', 'Remove', {_ID}),
('button_reorder', 'language', 'Reorder', {_ID}),
('button_return', 'language', 'Return', {_ID}),
('button_shopping', 'language', 'Continue Shopping', {_ID}),
('button_search', 'language', 'Search', {_ID}),
('button_shipping', 'language', 'Apply Shipping', {_ID}),
('button_submit', 'language', 'Submit', {_ID}),
('button_guest', 'language', 'Guest Checkout', {_ID}),
('button_view', 'language', 'View', {_ID}),
('button_voucher', 'language', 'Apply Gift Certificate', {_ID}),
('button_upload', 'language', 'Upload File', {_ID}),
('button_reward', 'language', 'Apply Points', {_ID}),
('button_quote', 'language', 'Get Quotes', {_ID}),
('button_list', 'language', 'List', {_ID}),
('button_grid', 'language', 'Grid', {_ID}),
('button_map', 'language', 'View Google Map', {_ID}),
('error_exception', 'language', 'Error Code(%s): %s in %s on line %s', {_ID}),
('error_upload_1', 'language', 'Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!', {_ID}),
('error_upload_2', 'language', 'Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!', {_ID}),
('error_upload_3', 'language', 'Warning: The uploaded file was only partially uploaded!', {_ID}),
('error_upload_4', 'language', 'Warning: No file was uploaded!', {_ID}),
('error_upload_6', 'language', 'Warning: Missing a temporary folder!', {_ID}),
('error_upload_7', 'language', 'Warning: Failed to write file to disk!', {_ID}),
('error_upload_8', 'language', 'Warning: File upload stopped by extension!', {_ID}),
('error_upload_999', 'language', 'Warning: No error code available!', {_ID}),
('error_curl', 'language', 'CURL: Error Code(%s): %s', {_ID}),
('heading_title', 'language', 'Product Returns', {_ID}),
('text_account', 'language', 'Account', {_ID}),
('text_return', 'language', 'Return Information', {_ID}),
('text_return_detail', 'language', 'Return Details', {_ID}),
('text_description', 'language', 'Please complete the form below to request an RMA number.', {_ID}),
('text_order', 'language', 'Order Information', {_ID}),
('text_product', 'language', 'Product', {_ID}),
('text_reason', 'language', 'Reason', {_ID}),
('text_message', 'language', '<p>Thank you for submitting your return request. Your request has been sent to the relevant department for processing.</p><p> You will be notified via e-mail as to the status of your request.</p>', {_ID}),
('text_return_id', 'language', 'Return ID:', {_ID}),
('text_order_id', 'language', 'Order ID:', {_ID}),
('text_date_ordered', 'language', 'Order Date:', {_ID}),
('text_status', 'language', 'Status:', {_ID}),
('text_date_added', 'language', 'Date Added:', {_ID}),
('text_comment', 'language', 'Return Comments:', {_ID}),
('text_history', 'language', 'Return History', {_ID}),
('text_empty', 'language', 'You have not made any previous returns!', {_ID}),
('text_agree', 'language', 'I have read and agree to the <a href=\"%s\" class=\"agree\"><b>%s</b></a>', {_ID}),
('column_return_id', 'language', 'Return ID', {_ID}),
('column_order_id', 'language', 'Order ID', {_ID}),
('column_status', 'language', 'Status', {_ID}),
('column_date_added', 'language', 'Date Added', {_ID}),
('column_customer', 'language', 'Customer', {_ID}),
('column_product', 'language', 'Product Name', {_ID}),
('column_model', 'language', 'Model', {_ID}),
('column_quantity', 'language', 'Quantity', {_ID}),
('column_price', 'language', 'Price', {_ID}),
('column_opened', 'language', 'Opened', {_ID}),
('column_comment', 'language', 'Comment', {_ID}),
('column_reason', 'language', 'Reason', {_ID}),
('column_action', 'language', 'Action', {_ID}),
('entry_order_id', 'language', 'Order ID', {_ID}),
('entry_date_ordered', 'language', 'Order Date', {_ID}),
('entry_firstname', 'language', 'First Name', {_ID}),
('entry_lastname', 'language', 'Last Name', {_ID}),
('entry_email', 'language', 'E-Mail', {_ID}),
('entry_telephone', 'language', 'Telephone', {_ID}),
('entry_product', 'language', 'Product Name', {_ID}),
('entry_model', 'language', 'Product Code', {_ID}),
('entry_quantity', 'language', 'Quantity', {_ID}),
('entry_reason', 'language', 'Reason for Return', {_ID}),
('entry_opened', 'language', 'Product is opened', {_ID}),
('entry_fault_detail', 'language', 'Faulty or other details', {_ID}),
('text_error', 'language', 'The returns you requested could not be found!', {_ID}),
('error_order_id', 'language', 'Order ID required!', {_ID}),
('error_firstname', 'language', 'First Name must be between 1 and 32 characters!', {_ID}),
('error_lastname', 'language', 'Last Name must be between 1 and 32 characters!', {_ID}),
('error_email', 'language', 'E-Mail Address does not appear to be valid!', {_ID}),
('error_telephone', 'language', 'Telephone must be between 3 and 32 characters!', {_ID}),
('error_product', 'language', 'Product Name must be greater than 3 and less than 255 characters!', {_ID}),
('error_model', 'language', 'Product Model must be greater than 3 and less than 64 characters!', {_ID}),
('error_reason', 'language', 'You must select a return product reason!', {_ID}),
('error_agree', 'language', 'Warning: You must agree to the %s!', {_ID}),
('text_action', 'language', 'Login into admin for further details', {_ID}),
('text_email', 'language', 'E-Mail:', {_ID}),
('text_name', 'language', 'Name:', {_ID}),
('text_greeting', 'language', 'A new product return has been placed at: {$store_name}', {_ID}),
('text_date', 'language', 'Date:', {_ID}),
('text_model', 'language', 'Model:', {_ID}),
('text_opened', 'language', 'Opened:', {_ID}),
('text_order_date', 'language', 'Order Date', {_ID}),
('text_order_total', 'language', 'Order Total', {_ID}),
('text_quantity', 'language', 'Quantity', {_ID}),
('text_return_date', 'language', 'Return Details', {_ID}),
('text_subject', 'language', 'New return for: {$store_name}', {_ID}),
('text_telephone', 'language', 'Telephone', {_ID}),
('text_rating', 'language', 'Rating', {_ID});