INSERT INTO `oc_emailtemplate` SET
`emailtemplate_key` = 'admin.voucher',
`emailtemplate_label` = 'Admin - Gift Voucher',
`emailtemplate_type` = 'order',
`emailtemplate_template` = '',
`emailtemplate_mail_to` = '',
`emailtemplate_mail_cc` = '',
`emailtemplate_mail_bcc` = '',
`emailtemplate_mail_from` = '',
`emailtemplate_mail_html` = 1,
`emailtemplate_mail_plain_text` = 0,
`emailtemplate_mail_sender` = '',
`emailtemplate_mail_replyto` = '',
`emailtemplate_mail_replyto_name` = '',
`emailtemplate_mail_attachment` = '',
`emailtemplate_attach_invoice` = 0,
`emailtemplate_language_files` = 'extension/mail/voucher',
`emailtemplate_wrapper_tpl` = '',
`emailtemplate_status` = 1,
`emailtemplate_default` = 1,
`emailtemplate_shortcodes` = 0,
`emailtemplate_showcase` = 1,
`emailtemplate_condition` = '',
`emailtemplate_modified` = NOW(),
`emailtemplate_log` = 0,
`emailtemplate_view_browser` = 0,
`emailtemplate_config_id` = 0,
`store_id` = NULL,
`customer_group_id` = 0,
`order_status_id` = 0,
`event_id` = '';

INSERT INTO `oc_emailtemplate_description` SET 
`emailtemplate_id` = {_ID},
`language_id` = 0,
`emailtemplate_description_subject` = '',
`emailtemplate_description_preview` = '{$text_from}',
`emailtemplate_description_content1` = '&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:auto;&quot;&gt;\r\n    &lt;tbody&gt;\r\n        &lt;tr&gt;\r\n            &lt;td width=&quot;2&quot;&gt; &lt;/td&gt;\r\n            &lt;td class=&quot;heading2&quot;&gt;&lt;strong&gt;{$text_heading}&lt;/strong&gt;&lt;/td&gt;\r\n        &lt;/tr&gt;\r\n        &lt;tr&gt;\r\n            &lt;td height=&quot;3&quot; style=&quot;font-size:1px; line-height:0;&quot; width=&quot;2&quot;&gt; &lt;/td&gt;\r\n            &lt;td height=&quot;3&quot; style=&quot;font-size:1px; line-height:0;&quot;&gt; &lt;/td&gt;\r\n        &lt;/tr&gt;\r\n        &lt;tr&gt;\r\n            &lt;td bgcolor=&quot;#CCCCCC&quot; height=&quot;1&quot; style=&quot;font-size:1px; line-height:0;&quot; width=&quot;2&quot;&gt; &lt;/td&gt;\r\n            &lt;td bgcolor=&quot;#CCCCCC&quot; height=&quot;1&quot; style=&quot;font-size:1px; line-height:0;&quot;&gt; &lt;/td&gt;\r\n        &lt;/tr&gt;\r\n        &lt;tr&gt;\r\n            &lt;td height=&quot;15&quot; style=&quot;font-size:1px; line-height:0;&quot; width=&quot;2&quot;&gt; &lt;/td&gt;\r\n            &lt;td height=&quot;15&quot; style=&quot;font-size:1px; line-height:0;&quot;&gt; &lt;/td&gt;\r\n        &lt;/tr&gt;\r\n    &lt;/tbody&gt;\r\n&lt;/table&gt;\r\n&lt;div style=&quot;float: right; margin-left: 20px;&quot;&gt;\r\n    &lt;a href=&quot;{$store_url}&quot; title=&quot;{$store_name}&quot;&gt;&lt;img alt=&quot;&quot; border=&quot;0&quot; height=&quot;{$image_height}&quot; src=&quot;{$image}&quot; style=&quot;display:inline;&quot; width=&quot;{$image_width}&quot;&gt; &lt;/a&gt;\r\n&lt;/div&gt;{$text_greeting}&lt;br&gt;\r\n&lt;br&gt;\r\n{$text_from}&lt;br&gt;\r\n&lt;br&gt;\r\n{$text_message}&lt;br&gt;\r\n{$message}&lt;br&gt;\r\n \r\n&lt;div class=&quot;link&quot; style=&quot;padding-top:4px;padding-bottom:4px;&quot;&gt;\r\n    {$text_redeem}&lt;br&gt;\r\n&lt;a href=&quot;{$store_url}&quot; target=&quot;_blank&quot;&gt;&lt;b&gt;{$store_url}&lt;/b&gt; &lt;/a&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;last&quot;&gt;\r\n    &lt;br&gt;\r\n    {$text_footer}\r\n&lt;/div&gt;',
`emailtemplate_description_content2` = '',
`emailtemplate_description_content3` = '',
`emailtemplate_description_comment` = '',
`emailtemplate_description_unsubscribe_text` = '';
